import type { ToolcraftControlSectionInventoryEntry } from "./types";

export const appControlSectionInventory: readonly ToolcraftControlSectionInventoryEntry[] = [
  {
    entity: "Image Library",
    entityId: "source-material",
    groupingReason: "Upload and manage source images in your image library.",
    id: "source-material",
    targets: ["source.image"],
    title: "Image Library",
  },
  {
    entity: "Creative Effects",
    entityId: "effects-gallery",
    groupingReason: "Browse and select creative visual style presets from the preset gallery.",
    id: "effects-gallery",
    targets: ["effect.selected"],
    title: "Creative Effects",
  },
  {
    entity: "Tonal & Monochrome Adjustments",
    entityId: "effects-tonal",
    groupingReason: "Tune parameters for black and white, duotone, posterize, and film grain effects.",
    id: "effects-tonal",
    targets: [
      "bw.contrast",
      "bw.warmth",
      "duotone.shadowColor",
      "duotone.highlightColor",
      "duotone.contrast",
      "posterize.levels",
      "grain.intensity",
      "tonal.reset",
    ],
    title: "Tonal & Monochrome Adjustments",
  },
  {
    entity: "Print & Film Adjustments",
    entityId: "effects-artistic",
    groupingReason: "Tune parameters for halftone and vintage film stylization effects.",
    id: "effects-artistic",
    targets: [
      "halftone.dotSize",
      "halftone.contrast",
      "halftone.angle",
      "halftone.density",
      "halftone.brightness",
      "vintageFilm.grain",
      "vintageFilm.fade",
      "vintageFilm.contrast",
      "vintageFilm.saturation",
      "vintageFilm.vignette",
    ],
    title: "Print & Film Adjustments",
  },
  {
    entity: "Graphic & Plate Adjustments",
    entityId: "effects-graphic",
    groupingReason: "Tune screen print color plates, registration offsets, and line art ink contours.",
    id: "effects-graphic",
    targets: [
      "screenPrint.inkColor1",
      "screenPrint.inkColor2",
      "screenPrint.inkDensity",
      "screenPrint.halftoneSize",
      "screenPrint.grain",
      "screenPrint.contrast",
      "screenPrint.registrationOffset",
      "lineArt.edgeThreshold",
      "lineArt.lineWeight",
      "lineArt.invert",
    ],
    title: "Graphic & Plate Adjustments",
  },
  {
    entity: "Digital & Matrix Adjustments",
    entityId: "effects-digital",
    groupingReason: "Tune digital glitch displacement, pixelation mosaic blocks, and ASCII matrix terminals.",
    id: "effects-digital",
    targets: [
      "glitch.intensity",
      "glitch.rgbShift",
      "glitch.noise",
      "glitch.scanlines",
      "glitch.distortion",
      "pixelate.blockSize",
      "ascii.fontSize",
      "ascii.characterDensity",
      "ascii.colorMode",
      "digital.reset",
    ],
    title: "Digital & Matrix Adjustments",
  },
  {
    entity: "Background",
    entityId: "background-section",
    groupingReason: "Configure background color and export background transparency.",
    id: "background-section",
    targets: ["export.includeBackground", "appearance.background"],
    title: "Background",
  },
  {
    entity: "Image Export",
    entityId: "image-export.part-export-image-format-1k2loow",
    groupingReason: "Configure export image format and resolution.",
    id: "image-export.part-export-image-format-1k2loow",
    targets: ["export.image.format", "export.image.resolution"],
    title: "Image Export",
  },
];
