import type { ToolcraftComponentAcceptance } from "./types";

export const effectControlsAcceptanceItems: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "adjusts monochrome tonal contrast curve",
    browser: true,
    browserTestName: "browser: user drags monochrome contrast slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Tonal contrast between light and dark grayscale tones steepens or softens on the canvas.",
    fixture: "monochrome contrast slider",
    id: "control.bw-contrast",
    kind: "control",
    target: "bw.contrast",
    userAction: "Drag the Monochrome contrast slider in Tonal Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts monochrome warmth temperature tint",
    browser: true,
    browserTestName: "browser: user drags monochrome warmth slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Monochrome tones shift towards warm sepia or cool cyan tinting on the canvas.",
    fixture: "monochrome warmth slider",
    id: "control.bw-warmth",
    kind: "control",
    target: "bw.warmth",
    userAction: "Drag the Warmth slider in Tonal Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "sets duotone shadow mapping color",
    browser: true,
    browserTestName: "browser: user changes duotone shadow color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Dark tones of the image re-map to the selected shadow color.",
    fixture: "duotone shadow color picker",
    id: "control.duotone-shadow-color",
    kind: "control",
    target: "duotone.shadowColor",
    userAction: "Pick a new shadow color in Tonal Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "sets duotone highlight mapping color",
    browser: true,
    browserTestName: "browser: user changes duotone highlight color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Bright tones of the image re-map to the selected highlight color.",
    fixture: "duotone highlight color picker",
    id: "control.duotone-highlight-color",
    kind: "control",
    target: "duotone.highlightColor",
    userAction: "Pick a new highlight color in Tonal Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts duotone gradient contrast curve",
    browser: true,
    browserTestName: "browser: user drags duotone contrast slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Gradient transition between shadow and highlight tones sharpens or softens.",
    fixture: "duotone contrast slider",
    id: "control.duotone-contrast",
    kind: "control",
    target: "duotone.contrast",
    userAction: "Drag the Duotone contrast slider in Tonal Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts posterize color levels step count",
    browser: true,
    browserTestName: "browser: user drags posterize color levels discrete slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Color quantization bands coarsen or refine on the canvas image.",
    fixture: "posterize color levels slider",
    id: "control.posterize-levels",
    kind: "control",
    target: "posterize.levels",
    userAction: "Select a level count on the Color levels discrete slider.",
  },
  {
    automated: true,
    automatedTestName: "adjusts film grain intensity parameter",
    browser: true,
    browserTestName: "browser: user drags grain intensity slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Noise grain texture amplitude increases or decreases over the image.",
    fixture: "film grain intensity slider",
    id: "control.grain-intensity",
    kind: "control",
    target: "grain.intensity",
    userAction: "Drag the Grain intensity slider in Tonal Adjustments.",
  },
  {
    actionCoverage: ["resetTonalEffect"],
    automated: true,
    automatedTestName: "resets selected tonal effect parameters to default values",
    browser: true,
    browserTestName: "browser: user clicks Reset Tonal Effect button",
    componentType: "actions",
    evidence: "command-side-effect",
    expectedObservable: "Parameter controls for the active tonal effect revert to registry default values.",
    fixture: "reset tonal effect button",
    id: "control.tonal-reset",
    kind: "control",
    target: "tonal.reset",
    userAction: "Click the Reset Tonal Effect action button.",
  },
  {
    automated: true,
    automatedTestName: "adjusts halftone dot size diameter",
    browser: true,
    browserTestName: "browser: user drags halftone dot size slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Printed halftone dot diameter scales across the canvas image.",
    fixture: "halftone dot size slider",
    id: "control.halftone-dot-size",
    kind: "control",
    target: "halftone.dotSize",
    userAction: "Drag the Dot size slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts halftone contrast curve",
    browser: true,
    browserTestName: "browser: user drags halftone contrast slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dot size gradient contrast sharpens or softens.",
    fixture: "halftone contrast slider",
    id: "control.halftone-contrast",
    kind: "control",
    target: "halftone.contrast",
    userAction: "Drag the Halftone contrast slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts halftone pattern rotation angle",
    browser: true,
    browserTestName: "browser: user drags halftone pattern angle slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Halftone dot grid rotates to the chosen angle.",
    fixture: "halftone pattern angle slider",
    id: "control.halftone-angle",
    kind: "control",
    target: "halftone.angle",
    userAction: "Drag the Pattern angle slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts halftone cell density spacing",
    browser: true,
    browserTestName: "browser: user drags halftone density slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Halftone grid cell density packs closer or widens.",
    fixture: "halftone density slider",
    id: "control.halftone-density",
    kind: "control",
    target: "halftone.density",
    userAction: "Drag the Halftone density slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts halftone brightness tone offset",
    browser: true,
    browserTestName: "browser: user drags halftone brightness slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Luminance tone offset brightens or darkens before dot sizing.",
    fixture: "halftone brightness slider",
    id: "control.halftone-brightness",
    kind: "control",
    target: "halftone.brightness",
    userAction: "Drag the Halftone brightness slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts vintage film grain intensity",
    browser: true,
    browserTestName: "browser: user drags vintage film grain slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Analog film grain texture amplitude adjusts on the image.",
    fixture: "vintage film grain slider",
    id: "control.vintage-film-grain",
    kind: "control",
    target: "vintageFilm.grain",
    userAction: "Drag the Film grain slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts vintage film faded matte black floor",
    browser: true,
    browserTestName: "browser: user drags vintage film fade slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Shadow black level lifts into a soft matte vintage tone.",
    fixture: "vintage film fade slider",
    id: "control.vintage-film-fade",
    kind: "control",
    target: "vintageFilm.fade",
    userAction: "Drag the Faded blacks slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts vintage film tonal contrast",
    browser: true,
    browserTestName: "browser: user drags vintage film contrast slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Film tone curve steepens or softens.",
    fixture: "vintage film contrast slider",
    id: "control.vintage-film-contrast",
    kind: "control",
    target: "vintageFilm.contrast",
    userAction: "Drag the Film contrast slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts vintage film color saturation",
    browser: true,
    browserTestName: "browser: user drags vintage film saturation slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Color saturation mutes or intensifies.",
    fixture: "vintage film saturation slider",
    id: "control.vintage-film-saturation",
    kind: "control",
    target: "vintageFilm.saturation",
    userAction: "Drag the Film saturation slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts vintage film radial lens vignette",
    browser: true,
    browserTestName: "browser: user drags vintage film vignette slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Optical edge darkening darkens corners of the canvas.",
    fixture: "vintage film vignette slider",
    id: "control.vintage-film-vignette",
    kind: "control",
    target: "vintageFilm.vignette",
    userAction: "Drag the Vignette slider in Print & Film Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "sets primary screen print ink color",
    browser: true,
    browserTestName: "browser: user changes primary ink color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Primary shadow/midtone screen ink recolors on the canvas.",
    fixture: "screen print primary ink color picker",
    id: "control.screen-print-ink-color1",
    kind: "control",
    target: "screenPrint.inkColor1",
    userAction: "Pick a primary ink color in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "sets secondary screen print ink color",
    browser: true,
    browserTestName: "browser: user changes secondary ink color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Secondary registration-offset screen ink recolors on the canvas.",
    fixture: "screen print secondary ink color picker",
    id: "control.screen-print-ink-color2",
    kind: "control",
    target: "screenPrint.inkColor2",
    userAction: "Pick a secondary ink color in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts screen print ink saturation density",
    browser: true,
    browserTestName: "browser: user drags screen print ink density slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Screen print ink opacity and coverage density scale.",
    fixture: "screen print ink density slider",
    id: "control.screen-print-ink-density",
    kind: "control",
    target: "screenPrint.inkDensity",
    userAction: "Drag the Ink density slider in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts screen print halftone grid size",
    browser: true,
    browserTestName: "browser: user drags screen print halftone size slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Screen print dot matrix coarsens or refines.",
    fixture: "screen print halftone size slider",
    id: "control.screen-print-halftone-size",
    kind: "control",
    target: "screenPrint.halftoneSize",
    userAction: "Drag the Halftone size slider in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts screen print paper fiber grain",
    browser: true,
    browserTestName: "browser: user drags screen print grain slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Tactile paper and ink fiber noise texture increases or decreases.",
    fixture: "screen print grain slider",
    id: "control.screen-print-grain",
    kind: "control",
    target: "screenPrint.grain",
    userAction: "Drag the Ink texture grain slider in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts screen print plate tonal contrast",
    browser: true,
    browserTestName: "browser: user drags screen print contrast slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Plate separation tone curve steepens or softens.",
    fixture: "screen print contrast slider",
    id: "control.screen-print-contrast",
    kind: "control",
    target: "screenPrint.contrast",
    userAction: "Drag the Plate contrast slider in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts screen print misaligned registration offset",
    browser: true,
    browserTestName: "browser: user drags screen print registration offset slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Secondary color plate shifts horizontally and vertically to simulate misaligned serigraphy.",
    fixture: "screen print registration offset slider",
    id: "control.screen-print-registration-offset",
    kind: "control",
    target: "screenPrint.registrationOffset",
    userAction: "Drag the Registration offset slider in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts line art contour edge threshold",
    browser: true,
    browserTestName: "browser: user drags line art edge threshold slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Sobel contour detection sensitivity filters subtle or prominent edges.",
    fixture: "line art edge threshold slider",
    id: "control.line-art-edge-threshold",
    kind: "control",
    target: "lineArt.edgeThreshold",
    userAction: "Drag the Edge threshold slider in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts line art contour line stroke weight",
    browser: true,
    browserTestName: "browser: user drags line art line weight slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Ink contour line stroke weight thickens or thins.",
    fixture: "line art line weight slider",
    id: "control.line-art-line-weight",
    kind: "control",
    target: "lineArt.lineWeight",
    userAction: "Drag the Line weight slider in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "toggles line art polarity inversion",
    browser: true,
    browserTestName: "browser: user toggles line art invert switch",
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Line art polarity toggles between black ink on white paper and white ink on black background.",
    fixture: "line art invert switch",
    id: "control.line-art-invert",
    kind: "control",
    target: "lineArt.invert",
    userAction: "Toggle the Invert polarity switch in Graphic & Plate Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts digital glitch amplitude intensity",
    browser: true,
    browserTestName: "browser: user drags glitch intensity slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Digital glitch distortion and noise amplitude scales across the canvas image.",
    fixture: "glitch intensity slider",
    id: "control.glitch-intensity",
    kind: "control",
    target: "glitch.intensity",
    userAction: "Drag the Glitch intensity slider in Digital & Matrix Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts chromatic RGB channel shift",
    browser: true,
    browserTestName: "browser: user drags glitch rgb shift slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Red, green, and blue color channels separate horizontally on the canvas.",
    fixture: "glitch rgb shift slider",
    id: "control.glitch-rgb-shift",
    kind: "control",
    target: "glitch.rgbShift",
    userAction: "Drag the RGB shift slider in Digital & Matrix Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts digital noise spike amplitude",
    browser: true,
    browserTestName: "browser: user drags glitch noise slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "High-frequency digital noise spikes intensify or soften.",
    fixture: "glitch noise slider",
    id: "control.glitch-noise",
    kind: "control",
    target: "glitch.noise",
    userAction: "Drag the Noise spikes slider in Digital & Matrix Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts CRT scanline overlay opacity",
    browser: true,
    browserTestName: "browser: user drags glitch scanlines slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Horizontal CRT raster scanlines darken alternating rows.",
    fixture: "glitch scanlines slider",
    id: "control.glitch-scanlines",
    kind: "control",
    target: "glitch.scanlines",
    userAction: "Drag the Scanlines slider in Digital & Matrix Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts glitch slice tear displacement",
    browser: true,
    browserTestName: "browser: user drags glitch distortion slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Horizontal band tears shift blocks of pixels sideways.",
    fixture: "glitch distortion slider",
    id: "control.glitch-distortion",
    kind: "control",
    target: "glitch.distortion",
    userAction: "Drag the Slice distortion slider in Digital & Matrix Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts 8-bit mosaic pixelation block size",
    browser: true,
    browserTestName: "browser: user drags pixelate block size slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Mosaic pixelation blocks scale up or down across the canvas image.",
    fixture: "pixelate block size slider",
    id: "control.pixelate-block-size",
    kind: "control",
    target: "pixelate.blockSize",
    userAction: "Drag the Pixelate block size slider in Digital & Matrix Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "adjusts ASCII character matrix font size",
    browser: true,
    browserTestName: "browser: user drags ASCII font size slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "ASCII terminal character cell grid scales in font size.",
    fixture: "ASCII font size slider",
    id: "control.ascii-font-size",
    kind: "control",
    target: "ascii.fontSize",
    userAction: "Drag the Matrix font size slider in Digital & Matrix Adjustments.",
  },
  {
    automated: true,
    automatedTestName: "selects ASCII character density set",
    browser: true,
    browserTestName: "browser: user selects character ramp dropdown option",
    componentType: "select",
    evidence: "rendered-pixels",
    expectedObservable: "Character density mapping changes between standard, blocks, and minimal ramps.",
    fixture: "ASCII character ramp select",
    id: "control.ascii-character-density",
    kind: "control",
    optionCoverage: ["standard", "blocks", "minimal"],
    target: "ascii.characterDensity",
    userAction: "Select a character density ramp from the Character ramp dropdown.",
  },
  {
    automated: true,
    automatedTestName: "selects ASCII color palette mode",
    browser: true,
    browserTestName: "browser: user selects ASCII color mode dropdown option",
    componentType: "select",
    evidence: "rendered-pixels",
    expectedObservable: "ASCII matrix palette switches between monochrome, full color, green phosphor, and amber CRT.",
    fixture: "ASCII color mode select",
    id: "control.ascii-color-mode",
    kind: "control",
    optionCoverage: ["monochrome", "color", "greenPhosphor", "amberCRT"],
    target: "ascii.colorMode",
    userAction: "Select a palette option from the Color mode dropdown in Digital & Matrix Adjustments.",
  },
  {
    actionCoverage: ["resetDigitalEffect"],
    automated: true,
    automatedTestName: "resets digital glitch, pixelate, and ASCII parameters to default values",
    browser: true,
    browserTestName: "browser: user clicks Reset Digital Effect button",
    componentType: "actions",
    evidence: "command-side-effect",
    expectedObservable: "Parameter controls for active digital effect revert to registry default values.",
    fixture: "reset digital effect button",
    id: "control.digital-reset",
    kind: "control",
    target: "digital.reset",
    userAction: "Click the Reset Digital Effect action button.",
  },
];
