import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";
import { asciiEffect } from "../effects/modules/ascii";
import { glitchEffect } from "../effects/modules/glitch";
import { pixelateEffect } from "../effects/modules/pixelate";

export const effectsDigitalSection: ToolcraftControlSectionSchema = {
  id: "effects-digital",
  title: "Digital & Matrix Adjustments",
  controls: {
    "glitch.intensity": {
      applicability: {
        all: [{ equals: "glitch", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (glitchEffect.defaultParameters.intensity as number) ?? 40,
      description: "Overall glitch amplitude.",
      label: "Glitch intensity",
      max: 100,
      min: 0,
      performanceReason: "Adjusts overall glitch amplitude.",
      performanceRole: "responsiveness",
      semanticGroup: "glitch",
      sliderValueKind: "continuous",
      step: 1,
      target: "glitch.intensity",
      type: "slider",
    },
    "glitch.rgbShift": {
      applicability: {
        all: [{ equals: "glitch", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (glitchEffect.defaultParameters.rgbShift as number) ?? 8,
      description: "Horizontal chromatic RGB channel offset.",
      label: "RGB shift",
      max: 30,
      min: 0,
      performanceReason: "Adjusts horizontal chromatic channel shift.",
      performanceRole: "responsiveness",
      semanticGroup: "glitch",
      sliderValueKind: "continuous",
      step: 1,
      target: "glitch.rgbShift",
      type: "slider",
    },
    "glitch.noise": {
      applicability: {
        all: [{ equals: "glitch", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (glitchEffect.defaultParameters.noise as number) ?? 20,
      description: "Digital noise burst amplitude.",
      label: "Noise spikes",
      max: 60,
      min: 0,
      performanceReason: "Adjusts digital noise burst amplitude.",
      performanceRole: "responsiveness",
      semanticGroup: "glitch",
      sliderValueKind: "continuous",
      step: 1,
      target: "glitch.noise",
      type: "slider",
    },
    "glitch.scanlines": {
      applicability: {
        all: [{ equals: "glitch", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (glitchEffect.defaultParameters.scanlines as number) ?? 30,
      description: "Horizontal CRT scanline overlay opacity.",
      label: "Scanlines",
      max: 80,
      min: 0,
      performanceReason: "Adjusts scanline overlay opacity.",
      performanceRole: "responsiveness",
      semanticGroup: "glitch",
      sliderValueKind: "continuous",
      step: 1,
      target: "glitch.scanlines",
      type: "slider",
    },
    "glitch.distortion": {
      applicability: {
        all: [{ equals: "glitch", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (glitchEffect.defaultParameters.distortion as number) ?? 15,
      description: "Horizontal block tear and slice displacement.",
      label: "Slice distortion",
      max: 50,
      min: 0,
      performanceReason: "Adjusts slice tear displacement.",
      performanceRole: "responsiveness",
      semanticGroup: "glitch",
      sliderValueKind: "continuous",
      step: 1,
      target: "glitch.distortion",
      type: "slider",
    },
    "pixelate.blockSize": {
      applicability: {
        all: [{ equals: "pixelate", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (pixelateEffect.defaultParameters.blockSize as number) ?? 12,
      description: "Pixel block grid dimension in pixels.",
      label: "Pixelate block size",
      max: 64,
      min: 2,
      performanceReason: "Adjusts pixel block grid dimension.",
      performanceRole: "responsiveness",
      semanticGroup: "pixelate",
      sliderValueKind: "continuous",
      step: 1,
      target: "pixelate.blockSize",
      type: "slider",
    },
    "ascii.fontSize": {
      applicability: {
        all: [{ equals: "ascii", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (asciiEffect.defaultParameters.fontSize as number) ?? 10,
      description: "ASCII character matrix cell font size in pixels.",
      label: "Matrix font size",
      max: 24,
      min: 6,
      performanceReason: "Adjusts ASCII font matrix size.",
      performanceRole: "responsiveness",
      semanticGroup: "ascii",
      sliderValueKind: "continuous",
      step: 1,
      target: "ascii.fontSize",
      type: "slider",
    },
    "ascii.characterDensity": {
      applicability: {
        all: [{ equals: "ascii", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (asciiEffect.defaultParameters.characterDensity as string) ?? "standard",
      description: "Character density ramp.",
      label: "Character ramp",
      options: [
        { label: "Standard (@%#*+=-:.)", value: "standard" },
        { label: "Blocks (█▓▒░)", value: "blocks" },
        { label: "Minimal (#+-.)", value: "minimal" },
      ],
      performanceReason: "Selects ASCII character density set.",
      performanceRole: "responsiveness",
      semanticGroup: "ascii",
      target: "ascii.characterDensity",
      type: "select",
    },
    "ascii.colorMode": {
      applicability: {
        all: [{ equals: "ascii", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (asciiEffect.defaultParameters.colorMode as string) ?? "monochrome",
      description: "CRT phosphor and chromatic palette color mode.",
      label: "Color mode",
      options: [
        { label: "Monochrome (White / Black)", value: "monochrome" },
        { label: "Full Color (RGB sampling)", value: "color" },
        { label: "Green Phosphor CRT", value: "greenPhosphor" },
        { label: "Amber Terminal CRT", value: "amberCRT" },
      ],
      performanceReason: "Selects ASCII output palette.",
      performanceRole: "responsiveness",
      semanticGroup: "ascii",
      target: "ascii.colorMode",
      type: "select",
    },
    "digital.reset": {
      actions: [
        {
          label: "Reset Digital Effect",
          value: "resetDigitalEffect",
        },
      ],
      applicability: {
        all: [
          {
            oneOf: ["glitch", "pixelate", "ascii"],
            target: "effect.selected",
          },
        ],
        mode: "conditional",
      },
      description: "Reset parameters for active digital effect to defaults.",
      label: "Reset",
      performanceReason: "Resets parameters for active digital effect.",
      performanceRole: "responsiveness",
      semanticGroup: "actions",
      target: "digital.reset",
      type: "actions",
    },
  },
};
