import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";
import { blackAndWhiteEffect } from "../effects/modules/black-and-white";
import { duotoneEffect } from "../effects/modules/duotone";
import { grainEffect } from "../effects/modules/grain";
import { posterizeEffect } from "../effects/modules/posterize";

export const effectsTonalSection: ToolcraftControlSectionSchema = {
  id: "effects-tonal",
  title: "Tonal & Monochrome Adjustments",
  controls: {
    "bw.contrast": {
      applicability: {
        all: [{ equals: "black-and-white", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (blackAndWhiteEffect.defaultParameters.contrast as number) ?? 1.2,
      description: "Monochrome luminance contrast balance.",
      label: "Monochrome contrast",
      max: 2.5,
      min: 0.5,
      performanceReason: "Adjusts monochrome tonal contrast curve.",
      performanceRole: "responsiveness",
      semanticGroup: "bw",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "bw.contrast",
      type: "slider",
    },
    "bw.warmth": {
      applicability: {
        all: [{ equals: "black-and-white", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (blackAndWhiteEffect.defaultParameters.warmth as number) ?? 0,
      description: "Warm (sepia) or cool (cyan) monochrome tone offset.",
      label: "Warmth",
      max: 50,
      min: -50,
      performanceReason: "Adjusts monochrome temperature tint offset.",
      performanceRole: "responsiveness",
      semanticGroup: "bw",
      sliderValueKind: "continuous",
      step: 1,
      target: "bw.warmth",
      type: "slider",
    },
    "duotone.shadowColor": {
      applicability: {
        all: [{ equals: "duotone", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (duotoneEffect.defaultParameters.shadowColor as string) ?? "#0f172a",
      description: "Color mapped to dark shadow tones.",
      label: "Shadow color",
      performanceReason: "Sets duotone shadow mapping color.",
      performanceRole: "responsiveness",
      semanticGroup: "duotone",
      target: "duotone.shadowColor",
      type: "color",
    },
    "duotone.highlightColor": {
      applicability: {
        all: [{ equals: "duotone", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (duotoneEffect.defaultParameters.highlightColor as string) ?? "#38bdf8",
      description: "Color mapped to bright highlight tones.",
      label: "Highlight color",
      performanceReason: "Sets duotone highlight mapping color.",
      performanceRole: "responsiveness",
      semanticGroup: "duotone",
      target: "duotone.highlightColor",
      type: "color",
    },
    "duotone.contrast": {
      applicability: {
        all: [{ equals: "duotone", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (duotoneEffect.defaultParameters.contrast as number) ?? 1.0,
      description: "Steepness of gradient transition curve.",
      label: "Duotone contrast",
      max: 2.0,
      min: 0.5,
      performanceReason: "Adjusts duotone gradient contrast curve.",
      performanceRole: "responsiveness",
      semanticGroup: "duotone",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "duotone.contrast",
      type: "slider",
    },
    "posterize.levels": {
      applicability: {
        all: [{ equals: "posterize", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (posterizeEffect.defaultParameters.levels as number) ?? 4,
      description: "Number of color steps per RGB channel.",
      label: "Color levels",
      max: 16,
      min: 2,
      performanceReason: "Adjusts channel quantization step count.",
      performanceRole: "responsiveness",
      semanticGroup: "posterize",
      sliderValueKind: "discrete",
      step: 1,
      target: "posterize.levels",
      type: "slider",
      variant: "discrete",
    },
    "grain.intensity": {
      applicability: {
        all: [{ equals: "grain", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (grainEffect.defaultParameters.intensity as number) ?? 35,
      description: "Film grain noise amplitude.",
      label: "Grain intensity",
      max: 100,
      min: 5,
      performanceReason: "Controls film grain noise amplitude.",
      performanceRole: "responsiveness",
      semanticGroup: "grain",
      sliderValueKind: "continuous",
      step: 1,
      target: "grain.intensity",
      type: "slider",
    },
    "tonal.reset": {
      actions: [
        {
          label: "Reset Tonal Effect",
          value: "resetTonalEffect",
        },
      ],
      applicability: {
        all: [
          {
            oneOf: ["black-and-white", "duotone", "posterize", "grain"],
            target: "effect.selected",
          },
        ],
        mode: "conditional",
      },
      description: "Reset parameters for active tonal effect to defaults.",
      label: "Reset",
      performanceReason: "Resets parameters for active tonal effect.",
      performanceRole: "responsiveness",
      semanticGroup: "actions",
      target: "tonal.reset",
      type: "actions",
    },
  },
};
