import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";
import { lineArtEffect } from "../effects/modules/line-art";
import { screenPrintEffect } from "../effects/modules/screen-print";

export const effectsGraphicSection: ToolcraftControlSectionSchema = {
  id: "effects-graphic",
  title: "Graphic & Plate Adjustments",
  controls: {
    "screenPrint.inkColor1": {
      applicability: {
        all: [{ equals: "screen-print", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (screenPrintEffect.defaultParameters.inkColor1 as string) ?? "#e11d48",
      description: "Primary screen ink color.",
      label: "Primary ink",
      performanceReason: "Sets primary screen ink color.",
      performanceRole: "responsiveness",
      semanticGroup: "screenprint",
      target: "screenPrint.inkColor1",
      type: "color",
    },
    "screenPrint.inkColor2": {
      applicability: {
        all: [{ equals: "screen-print", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (screenPrintEffect.defaultParameters.inkColor2 as string) ?? "#0284c7",
      description: "Secondary screen ink color.",
      label: "Secondary ink",
      performanceReason: "Sets secondary screen ink color.",
      performanceRole: "responsiveness",
      semanticGroup: "screenprint",
      target: "screenPrint.inkColor2",
      type: "color",
    },
    "screenPrint.inkDensity": {
      applicability: {
        all: [{ equals: "screen-print", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (screenPrintEffect.defaultParameters.inkDensity as number) ?? 1.0,
      description: "Ink saturation density.",
      label: "Ink density",
      max: 2.0,
      min: 0.5,
      performanceReason: "Adjusts screen ink saturation density.",
      performanceRole: "responsiveness",
      semanticGroup: "screenprint",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "screenPrint.inkDensity",
      type: "slider",
    },
    "screenPrint.halftoneSize": {
      applicability: {
        all: [{ equals: "screen-print", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (screenPrintEffect.defaultParameters.halftoneSize as number) ?? 8,
      description: "Halftone dot grid size.",
      label: "Halftone size",
      max: 20,
      min: 2,
      performanceReason: "Sets screen print halftone dot size.",
      performanceRole: "responsiveness",
      semanticGroup: "screenprint",
      sliderValueKind: "continuous",
      step: 1,
      target: "screenPrint.halftoneSize",
      type: "slider",
    },
    "screenPrint.grain": {
      applicability: {
        all: [{ equals: "screen-print", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (screenPrintEffect.defaultParameters.grain as number) ?? 20,
      description: "Paper and ink fiber noise texture.",
      label: "Ink texture grain",
      max: 60,
      min: 0,
      performanceReason: "Adjusts paper and ink fiber noise.",
      performanceRole: "responsiveness",
      semanticGroup: "screenprint",
      sliderValueKind: "continuous",
      step: 1,
      target: "screenPrint.grain",
      type: "slider",
    },
    "screenPrint.contrast": {
      applicability: {
        all: [{ equals: "screen-print", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (screenPrintEffect.defaultParameters.contrast as number) ?? 1.4,
      description: "Separation plate tonal contrast curve.",
      label: "Plate contrast",
      max: 2.5,
      min: 0.5,
      performanceReason: "Adjusts separation plate contrast.",
      performanceRole: "responsiveness",
      semanticGroup: "screenprint",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "screenPrint.contrast",
      type: "slider",
    },
    "screenPrint.registrationOffset": {
      applicability: {
        all: [{ equals: "screen-print", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (screenPrintEffect.defaultParameters.registrationOffset as number) ?? 3,
      description: "Misaligned color registration offset in pixels.",
      label: "Registration offset",
      max: 12,
      min: 0,
      performanceReason: "Sets misaligned color registration offset.",
      performanceRole: "responsiveness",
      semanticGroup: "screenprint",
      sliderValueKind: "continuous",
      step: 1,
      target: "screenPrint.registrationOffset",
      type: "slider",
    },
    "lineArt.edgeThreshold": {
      applicability: {
        all: [{ equals: "line-art", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (lineArtEffect.defaultParameters.edgeThreshold as number) ?? 45,
      description: "Contour edge detection threshold sensitivity.",
      label: "Edge threshold",
      max: 150,
      min: 10,
      performanceReason: "Adjusts contour detection threshold.",
      performanceRole: "responsiveness",
      semanticGroup: "lineart",
      sliderValueKind: "continuous",
      step: 1,
      target: "lineArt.edgeThreshold",
      type: "slider",
    },
    "lineArt.lineWeight": {
      applicability: {
        all: [{ equals: "line-art", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (lineArtEffect.defaultParameters.lineWeight as number) ?? 1.5,
      description: "Contour line thickness and stroke weight.",
      label: "Line weight",
      max: 5.0,
      min: 0.5,
      performanceReason: "Adjusts contour line stroke weight.",
      performanceRole: "responsiveness",
      semanticGroup: "lineart",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "lineArt.lineWeight",
      type: "slider",
    },
    "lineArt.invert": {
      applicability: {
        all: [{ equals: "line-art", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (lineArtEffect.defaultParameters.invert as boolean) ?? false,
      description: "Invert line polarity (white contours on black background).",
      label: "Invert polarity",
      performanceReason: "Toggles line art polarity inversion.",
      performanceRole: "responsiveness",
      semanticGroup: "lineart",
      target: "lineArt.invert",
      type: "switch",
    },
  },
};
