import type { ToolcraftControlSectionSchema } from "@/toolcraft/runtime";
import { halftoneEffect } from "../effects/modules/halftone";
import { vintageFilmEffect } from "../effects/modules/vintage-film";

export const effectsArtisticSection: ToolcraftControlSectionSchema = {
  id: "effects-artistic",
  title: "Print & Film Adjustments",
  controls: {
    "halftone.dotSize": {
      applicability: {
        all: [{ equals: "halftone", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (halftoneEffect.defaultParameters.dotSize as number) ?? 6,
      description: "Diameter of printed halftone dots.",
      label: "Dot size",
      max: 24,
      min: 2,
      performanceReason: "Adjusts diameter of printed halftone dots.",
      performanceRole: "responsiveness",
      semanticGroup: "halftone",
      sliderValueKind: "continuous",
      step: 1,
      target: "halftone.dotSize",
      type: "slider",
    },
    "halftone.contrast": {
      applicability: {
        all: [{ equals: "halftone", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (halftoneEffect.defaultParameters.contrast as number) ?? 1.3,
      description: "Steepness of dot size contrast curve.",
      label: "Halftone contrast",
      max: 2.5,
      min: 0.5,
      performanceReason: "Adjusts dot size contrast curve.",
      performanceRole: "responsiveness",
      semanticGroup: "halftone",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "halftone.contrast",
      type: "slider",
    },
    "halftone.angle": {
      applicability: {
        all: [{ equals: "halftone", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (halftoneEffect.defaultParameters.angle as number) ?? 45,
      description: "Screen rotation angle in degrees.",
      label: "Pattern angle",
      max: 90,
      min: 0,
      performanceReason: "Sets halftone screen angle.",
      performanceRole: "responsiveness",
      semanticGroup: "halftone",
      sliderValueKind: "continuous",
      step: 1,
      target: "halftone.angle",
      type: "slider",
    },
    "halftone.density": {
      applicability: {
        all: [{ equals: "halftone", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (halftoneEffect.defaultParameters.density as number) ?? 1.0,
      description: "Density spacing multiplier of halftone grid cells.",
      label: "Halftone density",
      max: 2.0,
      min: 0.5,
      performanceReason: "Adjusts density spacing of halftone cells.",
      performanceRole: "responsiveness",
      semanticGroup: "halftone",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "halftone.density",
      type: "slider",
    },
    "halftone.brightness": {
      applicability: {
        all: [{ equals: "halftone", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (halftoneEffect.defaultParameters.brightness as number) ?? 0,
      description: "Luminance tone offset before dot sizing.",
      label: "Halftone brightness",
      max: 50,
      min: -50,
      performanceReason: "Adjusts brightness tone offset.",
      performanceRole: "responsiveness",
      semanticGroup: "halftone",
      sliderValueKind: "continuous",
      step: 1,
      target: "halftone.brightness",
      type: "slider",
    },
    "vintageFilm.grain": {
      applicability: {
        all: [{ equals: "vintage-film", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (vintageFilmEffect.defaultParameters.grain as number) ?? 30,
      description: "Organic analog film grain intensity.",
      label: "Film grain",
      max: 80,
      min: 0,
      performanceReason: "Adjusts vintage film grain intensity.",
      performanceRole: "responsiveness",
      semanticGroup: "vintage",
      sliderValueKind: "continuous",
      step: 1,
      target: "vintageFilm.grain",
      type: "slider",
    },
    "vintageFilm.fade": {
      applicability: {
        all: [{ equals: "vintage-film", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (vintageFilmEffect.defaultParameters.fade as number) ?? 25,
      description: "Lifted matte black floor level.",
      label: "Faded blacks",
      max: 60,
      min: 0,
      performanceReason: "Adjusts faded black floor level.",
      performanceRole: "responsiveness",
      semanticGroup: "vintage",
      sliderValueKind: "continuous",
      step: 1,
      target: "vintageFilm.fade",
      type: "slider",
    },
    "vintageFilm.contrast": {
      applicability: {
        all: [{ equals: "vintage-film", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (vintageFilmEffect.defaultParameters.contrast as number) ?? 1.1,
      description: "Film tonal contrast curve.",
      label: "Film contrast",
      max: 2.0,
      min: 0.5,
      performanceReason: "Adjusts vintage film tonal contrast.",
      performanceRole: "responsiveness",
      semanticGroup: "vintage",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "vintageFilm.contrast",
      type: "slider",
    },
    "vintageFilm.saturation": {
      applicability: {
        all: [{ equals: "vintage-film", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (vintageFilmEffect.defaultParameters.saturation as number) ?? 0.8,
      description: "Color saturation level.",
      label: "Film saturation",
      max: 2.0,
      min: 0.0,
      performanceReason: "Adjusts color saturation level.",
      performanceRole: "responsiveness",
      semanticGroup: "vintage",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "vintageFilm.saturation",
      type: "slider",
    },
    "vintageFilm.vignette": {
      applicability: {
        all: [{ equals: "vintage-film", target: "effect.selected" }],
        mode: "conditional",
      },
      defaultValue: (vintageFilmEffect.defaultParameters.vignette as number) ?? 40,
      description: "Radial optical lens edge darkening.",
      label: "Vignette",
      max: 100,
      min: 0,
      performanceReason: "Adjusts lens edge darkening.",
      performanceRole: "responsiveness",
      semanticGroup: "vintage",
      sliderValueKind: "continuous",
      step: 1,
      target: "vintageFilm.vignette",
      type: "slider",
    },
  },
};
