import type { EffectStack } from "./asset";
import type { BackgroundState, BackgroundType } from "./look";
import { DEFAULT_BACKGROUND_STATE } from "./look";
import { normalizeLegacyBackgroundToBackgrounds } from "../generative/normalization";

/**
 * Selected Stage 1 subset of blend modes implemented according to
 * relevant W3C Compositing and Blending Level 1 specifications.
 */
export type BlendMode =
  | "normal"
  | "multiply"
  | "screen"
  | "overlay"
  | "darken"
  | "lighten"
  | "color-dodge"
  | "color-burn"
  | "hard-light"
  | "soft-light"
  | "difference"
  | "exclusion";

export const BLEND_MODE_OPTIONS = [
  { value: "normal", label: "Normal" },
  { value: "multiply", label: "Multiply" },
  { value: "screen", label: "Screen" },
  { value: "overlay", label: "Overlay" },
  { value: "darken", label: "Darken" },
  { value: "lighten", label: "Lighten" },
  { value: "color-dodge", label: "Color Dodge" },
  { value: "color-burn", label: "Color Burn" },
  { value: "hard-light", label: "Hard Light" },
  { value: "soft-light", label: "Soft Light" },
  { value: "difference", label: "Difference" },
  { value: "exclusion", label: "Exclusion" },
] as const;

export interface FrameDimensions {
  width: number;
  height: number;
  presetId?: string | null;
}

export interface FrameSizePreset {
  id: string;
  name: string;
  category: "Square" | "Free" | "Landscape" | "Portrait";
  width: number;
  height: number;
  aspectRatioLabel: string;
}

export interface LayerTransform {
  x: number; // Frame-space pixels, 0 = centered horizontally
  y: number; // Frame-space pixels, 0 = centered vertically
  scaleX: number; // 0.05 to 20.0, 1.0 = 100% of fitted base geometry
  scaleY: number; // 0.05 to 20.0, 1.0 = 100% of fitted base geometry
  rotation: number; // Degrees, [-180, 180], 0 = upright
}

export const DEFAULT_LAYER_TRANSFORM: LayerTransform = {
  x: 0,
  y: 0,
  scaleX: 1,
  scaleY: 1,
  rotation: 0,
};

export const BACKGROUND_ITEM_TYPES = [
  "solid",
  "linear-gradient",
  "radial-gradient",
  "dots",
  "grid",
] as const;

export type BackgroundItemType = (typeof BACKGROUND_ITEM_TYPES)[number];

// ---------------------------------------------------------------------------
// Unified Composition Model — Source Abstraction (Approved Architecture)
// ---------------------------------------------------------------------------

/**
 * ImageSource describes visual content generated from an immutable Asset bitmap.
 * Universal rule: If it creates pixels -> Source.
 */
export interface ImageSource {
  type: "image";
  assetId: string; // References immutable source Asset in assets store
}

/**
 * ProceduralSource describes algorithmic visual content generated by procedural shaders.
 * Universal rule: If it creates pixels -> Source.
 * Supported kinds: "solid" | "linear-gradient" | "radial-gradient" | "dots" | "grid".
 */
export interface ProceduralSource {
  type: "procedural";
  kind: BackgroundItemType;
  parameters: Record<string, unknown>;
  seed?: number;
}

/**
 * LayerSource describes what generates a Layer's visual content.
 * Universal rule: If it creates pixels -> Source.
 */
export type LayerSource = ImageSource | ProceduralSource;

// ---------------------------------------------------------------------------
// Single-Tier Group Model (Approved Architecture)
// ---------------------------------------------------------------------------

/**
 * Group organizes Layers within a Frame.
 * Universal rule: If it organizes visual objects -> Group.
 * v1: Single-tier grouping (Frame -> Group -> Layer[]).
 */
export interface Group {
  id: string;
  name: string;
  layerIds: string[];
  visible: boolean;
  locked: boolean;
  collapsed?: boolean;
  createdAt: number;
  updatedAt: number;
}

// ---------------------------------------------------------------------------
// Layer Architecture
// ---------------------------------------------------------------------------

export interface BaseLayer {
  id: string;
  name: string;
  visible: boolean;
  opacity: number; // 0.0 to 1.0
  blendMode: BlendMode; // Layer-level blend mode interacting with accumulated backdrop
  effectStack: EffectStack;
  locked?: boolean;
  groupId?: string | null;
  createdAt: number;
  updatedAt: number;
}

/**
 * Canonical Layer in the Unified Composition Model.
 *
 * Core rule:
 * If it creates pixels -> Source.
 * If it independently composites -> Layer.
 * If it changes pixels -> Effect.
 * If it organizes visual objects -> Group.
 * If it defines composition bounds -> Frame.
 *
 * Layer is the universal independently composited visual object.
 * Every Layer has exactly one Source (`Layer.source`), which is the canonical source of truth.
 *
 * CANONICAL ARCHITECTURE:
 * - Layer.source (Authoritative pixel generator: ImageSource | ProceduralSource)
 * - Layer metadata (id, name, visible, opacity, blendMode, effectStack, locked, groupId, createdAt, updatedAt)
 * - Layer.transform
 * - Layer.fit
 *
 * COMPATIBILITY ONLY (Phase 1 migration boundary):
 * The following fields exist strictly to support un-migrated downstream consumers (Phase 2 compositor,
 * Phase 3 studio state, Phase 4 UI). They are NOT part of the Unified Composition Model itself,
 * must NOT be treated as secondary sources of truth, and are scheduled for removal during downstream migrations:
 * - type
 * - assetId
 * - backgrounds
 * - sublayers
 * - backgroundMode
 * - backgroundConfig
 */
export interface Layer extends BaseLayer {
  /** Canonical source of truth: generates visual pixels for this Layer */
  source: LayerSource;
  transform?: LayerTransform;
  fit?: "contain" | "cover";

  // Legacy compatibility fields (Phase 1 migration boundary only — scheduled for removal during downstream migration)
  /** @deprecated Compatibility-only field for un-migrated Phase 2-4 consumers. Not canonical architecture; canonical source of truth is source.type. */
  type?: "image" | "generative" | "procedural";
  /** @deprecated Compatibility-only field for un-migrated Phase 2-4 consumers. Not canonical architecture; canonical source of truth is (source as ImageSource).assetId. */
  assetId?: string;
  /** @deprecated Compatibility-only field for un-migrated Phase 2-4 consumers. Not canonical architecture; procedural backgrounds are canonically modeled via ProceduralSource on Layer. */
  backgrounds?: BackgroundItem[];
  /** @deprecated Kept for backward compatibility and hydration migration only. Scheduled for removal during downstream migration. */
  sublayers?: BackgroundItem[];
  /** @deprecated Kept for backward compatibility and hydration migration only. Scheduled for removal during downstream migration. */
  backgroundMode?: BackgroundType;
  /** @deprecated Kept for backward compatibility and hydration migration only. Scheduled for removal during downstream migration. */
  backgroundConfig?: BackgroundState;
}

/**
 * @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers.
 * BackgroundItem represents an independent stackable background element
 * in the legacy background stack owned by GenerativeLayer.
 * Not canonical architecture; procedural visual elements are canonically represented by ProceduralSource on Layer.
 * Scheduled for removal when downstream systems migrate.
 */
export interface BackgroundItem {
  id: string;
  type: BackgroundItemType;
  enabled: boolean;
  opacity: number; // Clamped to [0.0, 1.0]
  blendMode: BlendMode; // W3C blend mode over preceding backgrounds
  parameters: Record<string, unknown>;
  name?: string;
  seed?: number;
}

/** @deprecated Legacy migration adapter. Use BackgroundItem instead */
export type GenerativeSublayer = BackgroundItem;
/** @deprecated Legacy migration adapter. Use BackgroundItemType instead */
export type GenerativeSublayerType = BackgroundItemType;

/**
 * @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers.
 * ImageLayer represents an imported visual asset placed within a Frame.
 * Legacy compatibility interface extending canonical Layer.
 * Canonical architecture: Layer with source: ImageSource.
 * Scheduled for removal when downstream systems migrate.
 */
export interface ImageLayer extends Layer {
  type: "image";
  assetId: string;
  fit: "contain" | "cover";
  transform?: LayerTransform;
}

/**
 * @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers.
 * GenerativeLayer represents procedural canvas background content.
 * Legacy compatibility interface extending canonical Layer.
 * Canonical architecture: Layer with source: ProceduralSource.
 * Scheduled for removal when downstream systems migrate.
 */
export interface GenerativeLayer extends Layer {
  type: "generative";
  backgrounds: BackgroundItem[];
}

/**
 * Frame represents a complete, bounded composition document.
 *
 * In the Unified Composition Model:
 * Project -> Frame -> (Group) -> Layer -> Source
 */
export interface Frame {
  id: string;
  name: string;
  dimensions: FrameDimensions;
  layers: Layer[]; // Ordered bottom-to-top (index 0 = backdrop, N-1 = foreground)
  groups?: Group[];
  activeLayerId: string | null;
  createdAt: number;
  updatedAt: number;
}

export const FRAME_SIZE_PRESETS: readonly FrameSizePreset[] = [
  { id: "1:1", name: "Square", category: "Square", width: 1080, height: 1080, aspectRatioLabel: "1:1" },
  { id: "4:5", name: "Portrait (4:5)", category: "Portrait", width: 1080, height: 1350, aspectRatioLabel: "4:5" },
  { id: "9:16", name: "Story / Reel (9:16)", category: "Portrait", width: 1080, height: 1920, aspectRatioLabel: "9:16" },
  { id: "16:9", name: "Landscape (16:9)", category: "Landscape", width: 1920, height: 1080, aspectRatioLabel: "16:9" },
  { id: "4:3", name: "Standard (4:3)", category: "Landscape", width: 1440, height: 1080, aspectRatioLabel: "4:3" },
  { id: "2:3", name: "Classic 35mm (2:3)", category: "Portrait", width: 1080, height: 1620, aspectRatioLabel: "2:3" },
] as const;

export const DEFAULT_FRAME_DIMENSIONS: FrameDimensions = {
  width: 1080,
  height: 1080,
  presetId: "1:1",
};

// ---------------------------------------------------------------------------
// Type Guards & Helpers
// ---------------------------------------------------------------------------

export function isImageSource(source: unknown): source is ImageSource {
  return (
    typeof source === "object" &&
    source !== null &&
    (source as ImageSource).type === "image" &&
    typeof (source as ImageSource).assetId === "string"
  );
}

export function isProceduralSource(source: unknown): source is ProceduralSource {
  return (
    typeof source === "object" &&
    source !== null &&
    (source as ProceduralSource).type === "procedural" &&
    typeof (source as ProceduralSource).kind === "string" &&
    typeof (source as ProceduralSource).parameters === "object"
  );
}

export function isImageLayer(layer: Layer): layer is ImageLayer {
  return layer.type === "image" || (Boolean(layer.source) && isImageSource(layer.source));
}

export function isGenerativeLayer(layer: Layer): layer is GenerativeLayer {
  return layer.type === "generative";
}

// ---------------------------------------------------------------------------
// Layer & Frame Factories
// ---------------------------------------------------------------------------

/**
 * Synthesizes a canonical backdrop Layer for a Frame.
 *
 * In the Unified Composition Model:
 * The backdrop is an ordinary canonical Layer whose pixels originate from a ProceduralSource,
 * fulfilling the background visual role based on its position and creative intent (no special
 * background type is required).
 *
 * Architectural flow:
 * Background role -> ordinary Layer -> ProceduralSource
 * (NOT: GenerativeLayer -> BackgroundStack)
 *
 * Legacy background/generative fields (type: "generative", backgrounds, sublayers, backgroundMode,
 * backgroundConfig) are populated strictly as temporary compatibility data for un-migrated Phase 2-4 consumers.
 * They are not the canonical representation of the backdrop and are scheduled for removal during downstream migration.
 */
export function createDefaultBackdropLayer(backgroundConfig?: BackgroundState): Layer {
  const now = Date.now();
  const hasExplicitConfig = Boolean(backgroundConfig);
  const config = backgroundConfig ? { ...backgroundConfig } : { ...DEFAULT_BACKGROUND_STATE };
  const backgrounds = normalizeLegacyBackgroundToBackgrounds(config);
  const primaryBg = backgrounds[0];
  const source: ProceduralSource = primaryBg
    ? {
        type: "procedural",
        kind: primaryBg.type,
        parameters: { ...primaryBg.parameters },
        seed: primaryBg.seed,
      }
    : {
        type: "procedural",
        kind: "solid",
        parameters: { color: "#000000" },
      };

  return {
    id: typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `bg-${Date.now()}`,
    name: "Background",
    visible: hasExplicitConfig ? (config.visible ?? true) : false,
    opacity: 1.0,
    blendMode: "normal",
    effectStack: [],
    source,
    transform: { ...DEFAULT_LAYER_TRANSFORM },
    fit: "contain",
    groupId: null,
    // Legacy compatibility fields for un-migrated Phase 2-4 consumers
    type: "generative",
    backgrounds,
    sublayers: backgrounds,
    backgroundMode: config.type,
    backgroundConfig: config,
    createdAt: now,
    updatedAt: now,
  };
}

/** @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers. Use createDefaultBackdropLayer instead. */
export function createDefaultGenerativeLayer(backgroundConfig?: BackgroundState): GenerativeLayer {
  const backdrop = createDefaultBackdropLayer(backgroundConfig);
  delete (backdrop as any).source;
  return backdrop as GenerativeLayer;
}

/**
 * @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers.
 * Use createLayer({ name, source: { type: "image", assetId }, ... }) instead.
 * Creates a Layer referencing an immutable source asset and populates ImageSource alongside
 * legacy compatibility fields (type: "image", assetId).
 */
export function createImageLayer(
  assetId: string,
  name?: string,
  effectStack: EffectStack = [],
  fit: "contain" | "cover" = "contain",
  transform?: Partial<LayerTransform>,
  groupId?: string | null
): ImageLayer {
  const now = Date.now();
  return {
    id: typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? crypto.randomUUID()
      : `layer-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    name: name || "Image Layer",
    visible: true,
    opacity: 1.0,
    blendMode: "normal",
    effectStack: [...effectStack],
    source: {
      type: "image",
      assetId,
    },
    fit,
    transform: {
      x: transform && Number.isFinite(transform.x) ? transform.x! : DEFAULT_LAYER_TRANSFORM.x,
      y: transform && Number.isFinite(transform.y) ? transform.y! : DEFAULT_LAYER_TRANSFORM.y,
      scaleX: transform && Number.isFinite(transform.scaleX) ? Math.max(0.05, Math.min(20, transform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
      scaleY: transform && Number.isFinite(transform.scaleY) ? Math.max(0.05, Math.min(20, transform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
      rotation: transform && Number.isFinite(transform.rotation) ? transform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
    },
    groupId: groupId ?? null,
    // Legacy compatibility fields
    type: "image",
    assetId,
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Creates a canonical Layer in the Unified Composition Model.
 *
 * Every Layer requires exactly one canonical LayerSource (`source`), which is the authoritative
 * pixel generator.
 *
 * Migration boundary note: This factory intentionally populates explicitly deprecated compatibility
 * fields (type, assetId) because un-migrated downstream consumers (Phase 2 compositor, Phase 3 studio state,
 * Phase 4 UI) still require them during Phase 1. These fields are migration adapters only, not canonical architecture,
 * and `layer.source` remains the sole canonical source of truth.
 */
export function createLayer(params: {
  id?: string;
  name: string;
  source: LayerSource;
  visible?: boolean;
  opacity?: number;
  blendMode?: BlendMode;
  effectStack?: EffectStack;
  transform?: Partial<LayerTransform>;
  fit?: "contain" | "cover";
  locked?: boolean;
  groupId?: string | null;
}): Layer {
  const now = Date.now();
  const baseId =
    params.id ||
    (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? crypto.randomUUID()
      : `layer-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`);

  const transform: LayerTransform = {
    x: params.transform && Number.isFinite(params.transform.x) ? params.transform.x! : DEFAULT_LAYER_TRANSFORM.x,
    y: params.transform && Number.isFinite(params.transform.y) ? params.transform.y! : DEFAULT_LAYER_TRANSFORM.y,
    scaleX: params.transform && Number.isFinite(params.transform.scaleX) ? Math.max(0.05, Math.min(20, params.transform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
    scaleY: params.transform && Number.isFinite(params.transform.scaleY) ? Math.max(0.05, Math.min(20, params.transform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
    rotation: params.transform && Number.isFinite(params.transform.rotation) ? params.transform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
  };

  const layer: Layer = {
    id: baseId,
    name: params.name,
    visible: params.visible ?? true,
    opacity: typeof params.opacity === "number" ? Math.max(0, Math.min(1, params.opacity)) : 1.0,
    blendMode: params.blendMode ?? "normal",
    effectStack: params.effectStack ? [...params.effectStack] : [],
    locked: params.locked ?? false,
    groupId: params.groupId ?? null,
    source: params.source,
    fit: params.fit || "contain",
    transform,
    createdAt: now,
    updatedAt: now,
  };

  // Populate legacy compatibility fields for un-migrated consumers
  if (params.source.type === "image") {
    layer.type = "image";
    layer.assetId = params.source.assetId;
  } else if (params.source.type === "procedural") {
    layer.type = "procedural";
  }

  return layer;
}

/** @deprecated Legacy migration adapter. Use createLayer instead. */
export const createUniversalLayer = createLayer;

/** @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers. Use createLayer with ProceduralSource instead. */
export function createProceduralLayer(
  source: ProceduralSource,
  name?: string,
  options?: {
    id?: string;
    visible?: boolean;
    opacity?: number;
    blendMode?: BlendMode;
    effectStack?: EffectStack;
    transform?: Partial<LayerTransform>;
    fit?: "contain" | "cover";
    locked?: boolean;
    groupId?: string | null;
  }
): Layer {
  return createLayer({
    id: options?.id,
    name: name || `${source.kind.charAt(0).toUpperCase() + source.kind.slice(1)} Layer`,
    source,
    visible: options?.visible,
    opacity: options?.opacity,
    blendMode: options?.blendMode,
    effectStack: options?.effectStack,
    transform: options?.transform,
    fit: options?.fit,
    locked: options?.locked,
    groupId: options?.groupId,
  });
}

/**
 * Creates a single-tier Group container.
 */
export function createGroup(
  name: string,
  layerIds: string[] = [],
  options?: { id?: string; visible?: boolean; locked?: boolean; collapsed?: boolean }
): Group {
  const now = Date.now();
  return {
    id: options?.id || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? `group-${crypto.randomUUID()}`
      : `group-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`),
    name,
    layerIds: [...layerIds],
    visible: options?.visible ?? true,
    locked: options?.locked ?? false,
    collapsed: options?.collapsed ?? false,
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Synthesizes a new default Frame with a canonical backdrop Layer at index 0.
 */
export function createDefaultFrame(id?: string, name?: string): Frame {
  const now = Date.now();
  const baseBackdrop = createDefaultBackdropLayer();
  const frameId = id || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `frame-${now}`);
  return {
    id: frameId,
    name: name || "Frame 1",
    dimensions: { ...DEFAULT_FRAME_DIMENSIONS },
    layers: [baseBackdrop],
    groups: [],
    activeLayerId: baseBackdrop.id,
    createdAt: now,
    updatedAt: now,
  };
}

// ---------------------------------------------------------------------------
// Universal Composition Model Normalization & Migration
// ---------------------------------------------------------------------------

/**
 * Normalizes an individual Layer into one or more Universal Layers.
 *
 * In the Unified Composition Model:
 * 1. An ImageLayer (or legacy image record) maps to a single Layer with ImageSource(assetId).
 * 2. A legacy GenerativeLayer (with stackable backgrounds) expands into individual
 *    Layers with ProceduralSource, preserving visual order, parameters, blend modes,
 *    opacity, and visibility.
 * 3. An already-canonical Layer (with ImageSource or ProceduralSource)
 *    is returned cleanly without mutation or re-migration (idempotent).
 */
export function normalizeLayerToUniversal(layer: Layer | Record<string, unknown>): Layer[] {
  if (!layer || typeof layer !== "object") return [];

  const candidate = layer as Record<string, unknown>;
  const now = Date.now();

  // Case 1: Already canonical Layer with valid LayerSource
  // If the layer already has a canonical LayerSource (and does not contain an unexpanded multi-item legacy background stack)
  const hasMultipleLegacyBackgrounds =
    Array.isArray(candidate.backgrounds) && candidate.backgrounds.length > 1;

  if (candidate.source && !hasMultipleLegacyBackgrounds) {
    if (isImageSource(candidate.source) || (candidate.source as Record<string, unknown>).type === "image") {
      const rawSource = candidate.source as ImageSource;
      const assetId = (rawSource?.assetId || candidate.assetId || "") as string;
      const source: ImageSource = {
        type: "image",
        assetId,
      };

      const rawTransform = candidate.transform as Partial<LayerTransform> | undefined;
      const transform: LayerTransform = {
        x: rawTransform && Number.isFinite(rawTransform.x) ? rawTransform.x! : DEFAULT_LAYER_TRANSFORM.x,
        y: rawTransform && Number.isFinite(rawTransform.y) ? rawTransform.y! : DEFAULT_LAYER_TRANSFORM.y,
        scaleX: rawTransform && Number.isFinite(rawTransform.scaleX) ? Math.max(0.05, Math.min(20, rawTransform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
        scaleY: rawTransform && Number.isFinite(rawTransform.scaleY) ? Math.max(0.05, Math.min(20, rawTransform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
        rotation: rawTransform && Number.isFinite(rawTransform.rotation) ? rawTransform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
      };

      const imageLayer: ImageLayer = {
        id: (candidate.id as string) || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `img-${now}`),
        name: (candidate.name as string) || "Image Layer",
        visible: candidate.visible !== false,
        opacity: typeof candidate.opacity === "number" ? Math.max(0, Math.min(1, candidate.opacity as number)) : 1.0,
        blendMode: (candidate.blendMode as BlendMode) || "normal",
        effectStack: Array.isArray(candidate.effectStack) ? ([...candidate.effectStack] as EffectStack) : [],
        locked: Boolean(candidate.locked),
        groupId: (candidate.groupId as string | null | undefined) ?? null,
        type: "image",
        assetId,
        source,
        fit: (candidate.fit as "contain" | "cover") || "contain",
        transform,
        createdAt: (candidate.createdAt as number) || now,
        updatedAt: (candidate.updatedAt as number) || now,
      };

      return [imageLayer];
    }

    if (isProceduralSource(candidate.source) || (candidate.source as Record<string, unknown>).type === "procedural") {
      const procSource = candidate.source as ProceduralSource;
      const rawTransform = candidate.transform as Partial<LayerTransform> | undefined;
      const transform: LayerTransform = {
        x: rawTransform && Number.isFinite(rawTransform.x) ? rawTransform.x! : DEFAULT_LAYER_TRANSFORM.x,
        y: rawTransform && Number.isFinite(rawTransform.y) ? rawTransform.y! : DEFAULT_LAYER_TRANSFORM.y,
        scaleX: rawTransform && Number.isFinite(rawTransform.scaleX) ? Math.max(0.05, Math.min(20, rawTransform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
        scaleY: rawTransform && Number.isFinite(rawTransform.scaleY) ? Math.max(0.05, Math.min(20, rawTransform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
        rotation: rawTransform && Number.isFinite(rawTransform.rotation) ? rawTransform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
      };

      const procLayer: Layer = {
        id: (candidate.id as string) || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `proc-${now}`),
        name: (candidate.name as string) || (candidate.name === "Background" ? "Background" : `${procSource.kind.charAt(0).toUpperCase() + procSource.kind.slice(1)} Layer`),
        visible: candidate.visible !== false,
        opacity: typeof candidate.opacity === "number" ? Math.max(0, Math.min(1, candidate.opacity as number)) : 1.0,
        blendMode: (candidate.blendMode as BlendMode) || "normal",
        effectStack: Array.isArray(candidate.effectStack) ? ([...candidate.effectStack] as EffectStack) : [],
        locked: Boolean(candidate.locked),
        groupId: (candidate.groupId as string | null | undefined) ?? null,
        type: (candidate.type as "procedural" | "generative") || "procedural",
        source: {
          type: "procedural",
          kind: procSource.kind,
          parameters: { ...procSource.parameters },
          seed: procSource.seed,
        },
        fit: (candidate.fit as "contain" | "cover") || "contain",
        transform,
        createdAt: (candidate.createdAt as number) || now,
        updatedAt: (candidate.updatedAt as number) || now,
      };

      if (Array.isArray(candidate.backgrounds)) {
        procLayer.backgrounds = candidate.backgrounds as BackgroundItem[];
      }

      return [procLayer];
    }
  }

  // Case 2: Legacy GenerativeLayer (or any layer containing backgrounds stack)
  const isGenerative =
    candidate.type === "generative" ||
    Array.isArray(candidate.backgrounds) ||
    Boolean(candidate.backgroundConfig);

  if (isGenerative) {
    let bgItems: BackgroundItem[] = [];
    if (Array.isArray(candidate.backgrounds) && candidate.backgrounds.length > 0) {
      bgItems = candidate.backgrounds as BackgroundItem[];
    } else if (Array.isArray(candidate.sublayers) && candidate.sublayers.length > 0) {
      bgItems = candidate.sublayers as BackgroundItem[];
    } else if (candidate.backgroundConfig) {
      bgItems = normalizeLegacyBackgroundToBackgrounds(candidate.backgroundConfig as BackgroundState);
    }

    // If no background items were found, synthesize a default solid background preserving candidate.id
    if (bgItems.length === 0) {
      bgItems = [
        {
          id: (candidate.id as string) || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `bg-${Date.now()}`),
          type: "solid",
          enabled: candidate.visible !== false,
          opacity: typeof candidate.opacity === "number" ? (candidate.opacity as number) : 1.0,
          blendMode: (candidate.blendMode as BlendMode) || "normal",
          parameters: { color: "#000000" },
        },
      ];
    }

    const effectStack = Array.isArray(candidate.effectStack) ? (candidate.effectStack as EffectStack) : [];
    const layerLocked = Boolean(candidate.locked);
    const groupId = (candidate.groupId as string | null | undefined) ?? null;

    return bgItems.map((item, index) => {
      const proceduralSource: ProceduralSource = {
        type: "procedural",
        kind: item.type,
        parameters: item.parameters ? { ...item.parameters } : {},
        seed: item.seed,
      };

      const layerId = item.id || (index === 0 && candidate.id ? (candidate.id as string) : (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `bg-${now}-${index}`));

      const procLayer: Layer = {
        id: layerId,
        name: item.name || `${item.type.charAt(0).toUpperCase() + item.type.slice(1)} Background`,
        visible: item.enabled ?? true,
        opacity: typeof item.opacity === "number" ? Math.max(0, Math.min(1, item.opacity)) : 1.0,
        blendMode: item.blendMode || "normal",
        // The top procedural layer inherits any effectStack on the legacy GenerativeLayer
        effectStack: index === bgItems.length - 1 ? [...effectStack] : [],
        locked: layerLocked,
        groupId,
        type: "procedural",
        source: proceduralSource,
        transform: { ...DEFAULT_LAYER_TRANSFORM },
        createdAt: (candidate.createdAt as number) || now,
        updatedAt: (candidate.updatedAt as number) || now,
      };

      return procLayer;
    });
  }

  // Case 3: Legacy Image Layer (without source)
  const isImage =
    candidate.type === "image" ||
    typeof candidate.assetId === "string";

  if (isImage) {
    const assetId = (candidate.assetId || "") as string;
    const source: ImageSource = {
      type: "image",
      assetId,
    };

    const rawTransform = candidate.transform as Partial<LayerTransform> | undefined;
    const transform: LayerTransform = {
      x: rawTransform && Number.isFinite(rawTransform.x) ? rawTransform.x! : DEFAULT_LAYER_TRANSFORM.x,
      y: rawTransform && Number.isFinite(rawTransform.y) ? rawTransform.y! : DEFAULT_LAYER_TRANSFORM.y,
      scaleX: rawTransform && Number.isFinite(rawTransform.scaleX) ? Math.max(0.05, Math.min(20, rawTransform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
      scaleY: rawTransform && Number.isFinite(rawTransform.scaleY) ? Math.max(0.05, Math.min(20, rawTransform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
      rotation: rawTransform && Number.isFinite(rawTransform.rotation) ? rawTransform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
    };

    const imageLayer: ImageLayer = {
      id: (candidate.id as string) || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `img-${now}`),
      name: (candidate.name as string) || "Image Layer",
      visible: candidate.visible !== false,
      opacity: typeof candidate.opacity === "number" ? Math.max(0, Math.min(1, candidate.opacity as number)) : 1.0,
      blendMode: (candidate.blendMode as BlendMode) || "normal",
      effectStack: Array.isArray(candidate.effectStack) ? ([...candidate.effectStack] as EffectStack) : [],
      locked: Boolean(candidate.locked),
      groupId: (candidate.groupId as string | null | undefined) ?? null,
      type: "image",
      assetId,
      source,
      fit: (candidate.fit as "contain" | "cover") || "contain",
      transform,
      createdAt: (candidate.createdAt as number) || now,
      updatedAt: (candidate.updatedAt as number) || now,
    };

    return [imageLayer];
  }

  // Fallback: return candidate as-is if unrecognized
  return [candidate as unknown as Layer];
}

/**
 * Normalizes a complete Frame into the Unified Composition Model.
 *
 * Guaranteed Invariants:
 * 1. Every Layer has exactly one Source (ImageSource or ProceduralSource).
 * 2. Background is represented as one or more ordinary Layers with ProceduralSource.
 * 3. Single-tier groups are preserved or initialized as an empty array.
 * 4. Transforms are sanitized and clamped to valid bounds.
 * 5. activeLayerId is preserved or safely recovered.
 * 6. Idempotency: normalizing an already-normalized frame produces an identical structure.
 */
export function normalizeFrameToUniversalModel(frame: Frame): Frame {
  if (!frame || typeof frame !== "object") return frame;

  const normalizedLayers = (frame.layers || []).flatMap((layer) => normalizeLayerToUniversal(layer));

  // Recover or preserve activeLayerId
  let activeLayerId = frame.activeLayerId;
  const activeLayerExists = normalizedLayers.some((l) => l.id === activeLayerId);
  if (!activeLayerExists && normalizedLayers.length > 0) {
    activeLayerId = normalizedLayers[normalizedLayers.length - 1].id;
  }

  // Preserve groups
  const groups: Group[] = Array.isArray(frame.groups)
    ? frame.groups.map((g) => ({
        id: g.id,
        name: g.name,
        layerIds: [...g.layerIds],
        visible: g.visible ?? true,
        locked: g.locked ?? false,
        collapsed: g.collapsed ?? false,
        createdAt: g.createdAt || frame.createdAt,
        updatedAt: g.updatedAt || frame.updatedAt,
      }))
    : [];

  return {
    id: frame.id,
    name: frame.name || "Frame",
    dimensions: {
      width: frame.dimensions?.width || 1080,
      height: frame.dimensions?.height || 1080,
      presetId: frame.dimensions?.presetId ?? null,
    },
    layers: normalizedLayers,
    groups,
    activeLayerId: activeLayerId ?? (normalizedLayers[0]?.id || null),
    createdAt: frame.createdAt || Date.now(),
    updatedAt: frame.updatedAt || Date.now(),
  };
}
