import type { EffectStack } from "./asset";
import type { BackgroundState, BackgroundType } from "./look";
import { DEFAULT_BACKGROUND_STATE } from "./look";
import { normalizeLegacyBackgroundToBackgrounds } from "../generative/normalization";

/**
 * Selected Stage 1 subset of blend modes implemented according to
 * relevant W3C Compositing and Blending Level 1 specifications.
 */
export type BlendMode =
  | "normal"
  | "multiply"
  | "screen"
  | "overlay"
  | "darken"
  | "lighten"
  | "color-dodge"
  | "color-burn"
  | "hard-light"
  | "soft-light"
  | "difference"
  | "exclusion";

export const BLEND_MODE_OPTIONS = [
  { value: "normal", label: "Normal" },
  { value: "multiply", label: "Multiply" },
  { value: "screen", label: "Screen" },
  { value: "overlay", label: "Overlay" },
  { value: "darken", label: "Darken" },
  { value: "lighten", label: "Lighten" },
  { value: "color-dodge", label: "Color Dodge" },
  { value: "color-burn", label: "Color Burn" },
  { value: "hard-light", label: "Hard Light" },
  { value: "soft-light", label: "Soft Light" },
  { value: "difference", label: "Difference" },
  { value: "exclusion", label: "Exclusion" },
] as const;

export interface FrameDimensions {
  width: number;
  height: number;
  presetId?: string | null;
}

export interface FrameSizePreset {
  id: string;
  name: string;
  category: "Square" | "Free" | "Landscape" | "Portrait";
  width: number;
  height: number;
  aspectRatioLabel: string;
}

export interface LayerTransform {
  x: number; // Frame-space pixels, 0 = centered horizontally
  y: number; // Frame-space pixels, 0 = centered vertically
  scaleX: number; // 0.05 to 20.0, 1.0 = 100% of fitted base geometry
  scaleY: number; // 0.05 to 20.0, 1.0 = 100% of fitted base geometry
  rotation: number; // Degrees, [-180, 180], 0 = upright
}

export const DEFAULT_LAYER_TRANSFORM: LayerTransform = {
  x: 0,
  y: 0,
  scaleX: 1,
  scaleY: 1,
  rotation: 0,
};

export const BACKGROUND_ITEM_TYPES = [
  "solid",
  "linear-gradient",
  "radial-gradient",
  "dots",
  "grid",
] as const;

export type BackgroundItemType = (typeof BACKGROUND_ITEM_TYPES)[number];

// ---------------------------------------------------------------------------
// Unified Composition Model — Source Abstraction (Approved Architecture)
// ---------------------------------------------------------------------------

/**
 * ImageSource describes visual content generated from an immutable Asset bitmap.
 * Universal rule: If it creates pixels -> Source.
 */
export interface ImageSource {
  type: "image";
  assetId: string; // References immutable source Asset in assets store
}

/**
 * ProceduralSource describes algorithmic visual content generated by procedural shaders.
 * Universal rule: If it creates pixels -> Source.
 * Supported kinds: "solid" | "linear-gradient" | "radial-gradient" | "dots" | "grid".
 */
export interface ProceduralSource {
  type: "procedural";
  kind: BackgroundItemType;
  parameters: Record<string, unknown>;
  seed?: number;
}

/**
 * LayerSource describes what generates a Layer's visual content.
 * Universal rule: If it creates pixels -> Source.
 */
export type LayerSource = ImageSource | ProceduralSource;

// ---------------------------------------------------------------------------
// Single-Tier Group Model (Approved Architecture)
// ---------------------------------------------------------------------------

export type RootCompositionItem = Layer | Group;
export type FrameItem = RootCompositionItem;

/**
 * Group organizes Layers within a Frame.
 * Universal rule: If it organizes visual objects -> Group.
 * Canonical Model B: Single-tier physical containment (Frame.items -> Group -> children: Layer[]).
 */
export interface Group {
  id: string;
  name: string;
  children: Layer[];
  visible: boolean;
  locked: boolean;
  collapsed?: boolean;
  opacity: number; // 0.0 to 1.0 (default 1.0)
  blendMode: BlendMode; // Layer-level blend mode interacting with accumulated backdrop
  effectStack: EffectStack;
  transform?: LayerTransform;
  createdAt: number;
  updatedAt: number;
}

// ---------------------------------------------------------------------------
// Layer Architecture
// ---------------------------------------------------------------------------

export interface BaseLayer {
  id: string;
  name: string;
  visible: boolean;
  opacity: number; // 0.0 to 1.0
  blendMode: BlendMode; // Layer-level blend mode interacting with accumulated backdrop
  effectStack: EffectStack;
  locked?: boolean;
  createdAt: number;
  updatedAt: number;
}

/**
 * Canonical Layer in the Unified Composition Model.
 *
 * Core rule:
 * If it creates pixels -> Source.
 * If it independently composites -> Layer.
 * If it changes pixels -> Effect.
 * If it organizes visual objects -> Group.
 * If it defines composition bounds -> Frame.
 *
 * Layer is the universal independently composited visual object.
 * Every Layer has exactly one Source (`Layer.source`), which is the canonical source of truth.
 *
 * CANONICAL ARCHITECTURE:
 * - Layer.source (Authoritative pixel generator: ImageSource | ProceduralSource)
 * - Layer metadata (id, name, visible, opacity, blendMode, effectStack, locked, groupId, createdAt, updatedAt)
 * - Layer.transform
 * - Layer.fit
 *
 * COMPATIBILITY ONLY (Phase 1 migration boundary):
 * The following fields exist strictly to support un-migrated downstream consumers (Phase 2 compositor,
 * Phase 3 studio state, Phase 4 UI). They are NOT part of the Unified Composition Model itself,
 * must NOT be treated as secondary sources of truth, and are scheduled for removal during downstream migrations:
 * - type
 * - assetId
 * - backgrounds
 * - sublayers
 * - backgroundMode
 * - backgroundConfig
 */
export interface Layer extends BaseLayer {
  /** Canonical source of truth: generates visual pixels for this Layer */
  source: LayerSource;
  transform?: LayerTransform;
  fit?: "contain" | "cover";

  // Legacy compatibility fields (Phase 1 migration boundary only — scheduled for removal during downstream migration)
  /** @deprecated Compatibility-only field for un-migrated Phase 2-4 consumers. Not canonical architecture; canonical source of truth is source.type. */
  type?: "image" | "generative" | "procedural";
  /** @deprecated Compatibility-only field for un-migrated Phase 2-4 consumers. Not canonical architecture; canonical source of truth is (source as ImageSource).assetId. */
  assetId?: string;
}

/**
 * @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers.
 * BackgroundItem represents an independent stackable background element
 * in the legacy background stack owned by GenerativeLayer.
 * Not canonical architecture; procedural visual elements are canonically represented by ProceduralSource on Layer.
 * Scheduled for removal when downstream systems migrate.
 */
export interface BackgroundItem {
  id: string;
  type: BackgroundItemType;
  enabled: boolean;
  opacity: number; // Clamped to [0.0, 1.0]
  blendMode: BlendMode; // W3C blend mode over preceding backgrounds
  parameters: Record<string, unknown>;
  name?: string;
  seed?: number;
}

/** @deprecated Legacy migration adapter. Use BackgroundItem instead */
export type GenerativeSublayer = BackgroundItem;
/** @deprecated Legacy migration adapter. Use BackgroundItemType instead */
export type GenerativeSublayerType = BackgroundItemType;

/**
 * @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers.
 * ImageLayer represents an imported visual asset placed within a Frame.
 * Legacy compatibility interface extending canonical Layer.
 * Canonical architecture: Layer with source: ImageSource.
 * Scheduled for removal when downstream systems migrate.
 */
export interface ImageLayer extends Layer {
  type: "image";
  assetId: string;
  fit: "contain" | "cover";
  transform?: LayerTransform;
}

/**
 * @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers.
 * GenerativeLayer represents procedural canvas background content.
 * Legacy compatibility interface extending canonical Layer.
 * Canonical architecture: Layer with source: ProceduralSource.
 * Scheduled for removal when downstream systems migrate.
 */
export interface GenerativeLayer extends Layer {
  type: "generative";
  backgrounds: BackgroundItem[];
  sublayers?: BackgroundItem[];
  backgroundConfig?: BackgroundState;
  backgroundMode?: "solid" | "gradient" | "dots" | "grid" | "generative";
}

/**
 * Frame represents a complete, bounded composition document.
 *
 * In the Unified Composition Model:
 * Project -> Frame -> (Group) -> Layer -> Source
 */
export interface Frame {
  id: string;
  name: string;
  dimensions: FrameDimensions;
  items: (Layer | Group)[]; // Ordered bottom-to-top (index 0 = protected backdrop, N-1 = foreground)
  activeLayerId: string | null;
  createdAt: number;
  updatedAt: number;
}

export const FRAME_SIZE_PRESETS: readonly FrameSizePreset[] = [
  { id: "1:1", name: "Square", category: "Square", width: 1080, height: 1080, aspectRatioLabel: "1:1" },
  { id: "4:5", name: "Portrait (4:5)", category: "Portrait", width: 1080, height: 1350, aspectRatioLabel: "4:5" },
  { id: "9:16", name: "Story / Reel (9:16)", category: "Portrait", width: 1080, height: 1920, aspectRatioLabel: "9:16" },
  { id: "16:9", name: "Landscape (16:9)", category: "Landscape", width: 1920, height: 1080, aspectRatioLabel: "16:9" },
  { id: "4:3", name: "Standard (4:3)", category: "Landscape", width: 1440, height: 1080, aspectRatioLabel: "4:3" },
  { id: "2:3", name: "Classic 35mm (2:3)", category: "Portrait", width: 1080, height: 1620, aspectRatioLabel: "2:3" },
] as const;

export const DEFAULT_FRAME_DIMENSIONS: FrameDimensions = {
  width: 1080,
  height: 1080,
  presetId: "1:1",
};

// ---------------------------------------------------------------------------
// Type Guards & Helpers
// ---------------------------------------------------------------------------

export function isImageSource(source: unknown): source is ImageSource {
  return (
    typeof source === "object" &&
    source !== null &&
    (source as ImageSource).type === "image" &&
    typeof (source as ImageSource).assetId === "string"
  );
}

export function isProceduralSource(source: unknown): source is ProceduralSource {
  return (
    typeof source === "object" &&
    source !== null &&
    (source as ProceduralSource).type === "procedural" &&
    typeof (source as ProceduralSource).kind === "string" &&
    typeof (source as ProceduralSource).parameters === "object"
  );
}

export function isImageLayer(layer: Layer): layer is ImageLayer {
  return layer.type === "image" || (Boolean(layer.source) && isImageSource(layer.source));
}

export function isGenerativeLayer(layer: Layer): layer is GenerativeLayer {
  return layer.type === "generative";
}

export function isGroup(item: unknown): item is Group {
  return (
    typeof item === "object" &&
    item !== null &&
    Array.isArray((item as Group).children)
  );
}

export function isLayer(item: unknown): item is Layer {
  return (
    typeof item === "object" &&
    item !== null &&
    "source" in item &&
    !Array.isArray((item as any).children)
  );
}

// ---------------------------------------------------------------------------
// Layer & Frame Factories
// ---------------------------------------------------------------------------

/**
 * Synthesizes a canonical backdrop Layer for a Frame.
 *
 * In the Unified Composition Model:
 * The backdrop is an ordinary canonical Layer whose pixels originate from a ProceduralSource,
 * fulfilling the background visual role based on its position and creative intent (no special
 * background type is required).
 *
 * Architectural flow:
 * Background role -> ordinary Layer -> ProceduralSource
 * (NOT: GenerativeLayer -> BackgroundStack)
 *
 * Legacy background/generative fields (type: "generative", backgrounds, sublayers, backgroundMode,
 * backgroundConfig) are populated strictly as temporary compatibility data for un-migrated Phase 2-4 consumers.
 * They are not the canonical representation of the backdrop and are scheduled for removal during downstream migration.
 *
 * NOTE: The default `locked: true` is merely a UI convenience default for newly synthesized default frames,
 * NOT a structural protection. The procedural backdrop is an ordinary Layer that can be unlocked, edited,
 * reordered, and deleted.
 */
export function createDefaultBackdropLayer(backgroundConfig?: BackgroundState): Layer {
  const now = Date.now();
  const hasExplicitConfig = Boolean(backgroundConfig);
  const config = backgroundConfig ? { ...backgroundConfig } : { ...DEFAULT_BACKGROUND_STATE };
  const backgrounds = normalizeLegacyBackgroundToBackgrounds(config);
  const primaryBg = backgrounds[0];
  const source: ProceduralSource = primaryBg
    ? {
        type: "procedural",
        kind: primaryBg.type,
        parameters: { ...primaryBg.parameters },
        seed: primaryBg.seed,
      }
    : {
        type: "procedural",
        kind: "solid",
        parameters: { color: "#000000" },
      };

  const backdropId =
    typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? crypto.randomUUID()
      : `bg-${Date.now()}`;
  if (primaryBg) {
    primaryBg.id = backdropId;
  }

  return {
    id: backdropId,
    name: "Background",
    visible: hasExplicitConfig ? (config.visible ?? true) : false,
    opacity: 1.0,
    blendMode: "normal",
    effectStack: [],
    locked: true,
    source,
    transform: { ...DEFAULT_LAYER_TRANSFORM },
    fit: "contain",
    type: "procedural",
    createdAt: now,
    updatedAt: now,
  };
}

/** @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers. Use createDefaultBackdropLayer instead. */
export function createDefaultGenerativeLayer(backgroundConfig?: BackgroundState): GenerativeLayer {
  const backdrop = createDefaultBackdropLayer(backgroundConfig);
  delete (backdrop as any).source;
  return backdrop as GenerativeLayer;
}

/**
 * @deprecated Legacy migration adapter for un-migrated Phase 2-4 consumers.
 * Use createLayer({ name, source: { type: "image", assetId }, ... }) instead.
 * Creates a Layer referencing an immutable source asset and populates ImageSource alongside
 * legacy compatibility fields (type: "image", assetId).
 */
export function createImageLayer(
  assetId: string,
  name?: string,
  effectStack: EffectStack = [],
  fit: "contain" | "cover" = "contain",
  transform?: Partial<LayerTransform>
): ImageLayer {
  const now = Date.now();
  return {
    id: typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? crypto.randomUUID()
      : `layer-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    name: name || "Image Layer",
    visible: true,
    opacity: 1.0,
    blendMode: "normal",
    effectStack: [...effectStack],
    source: {
      type: "image",
      assetId,
    },
    fit,
    transform: {
      x: transform && Number.isFinite(transform.x) ? transform.x! : DEFAULT_LAYER_TRANSFORM.x,
      y: transform && Number.isFinite(transform.y) ? transform.y! : DEFAULT_LAYER_TRANSFORM.y,
      scaleX: transform && Number.isFinite(transform.scaleX) ? Math.max(0.05, Math.min(20, transform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
      scaleY: transform && Number.isFinite(transform.scaleY) ? Math.max(0.05, Math.min(20, transform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
      rotation: transform && Number.isFinite(transform.rotation) ? transform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
    },
    // Legacy compatibility fields
    type: "image",
    assetId,
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Creates a canonical Layer in the Unified Composition Model.
 *
 * Every Layer requires exactly one canonical LayerSource (`source`), which is the authoritative
 * pixel generator.
 *
 * Migration boundary note: This factory intentionally populates explicitly deprecated compatibility
 * fields (type, assetId) because un-migrated downstream consumers (Phase 2 compositor, Phase 3 studio state,
 * Phase 4 UI) still require them during Phase 1. These fields are migration adapters only, not canonical architecture,
 * and `layer.source` remains the sole canonical source of truth.
 */
export function createLayer(params: {
  id?: string;
  name: string;
  source: LayerSource;
  visible?: boolean;
  opacity?: number;
  blendMode?: BlendMode;
  effectStack?: EffectStack;
  transform?: Partial<LayerTransform>;
  fit?: "contain" | "cover";
  locked?: boolean;
  groupId?: string | null;
}): Layer {
  const now = Date.now();
  const baseId =
    params.id ||
    (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? crypto.randomUUID()
      : `layer-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`);

  const transform: LayerTransform = {
    x: params.transform && Number.isFinite(params.transform.x) ? params.transform.x! : DEFAULT_LAYER_TRANSFORM.x,
    y: params.transform && Number.isFinite(params.transform.y) ? params.transform.y! : DEFAULT_LAYER_TRANSFORM.y,
    scaleX: params.transform && Number.isFinite(params.transform.scaleX) ? Math.max(0.05, Math.min(20, params.transform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
    scaleY: params.transform && Number.isFinite(params.transform.scaleY) ? Math.max(0.05, Math.min(20, params.transform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
    rotation: params.transform && Number.isFinite(params.transform.rotation) ? params.transform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
  };

  const layer: Layer = {
    id: baseId,
    name: params.name,
    visible: params.visible ?? true,
    opacity: typeof params.opacity === "number" ? Math.max(0, Math.min(1, params.opacity)) : 1.0,
    blendMode: params.blendMode ?? "normal",
    effectStack: params.effectStack ? [...params.effectStack] : [],
    locked: params.locked ?? false,
    source: params.source,
    fit: params.fit || "contain",
    transform,
    createdAt: now,
    updatedAt: now,
  };

  // Populate legacy compatibility fields for un-migrated consumers
  if (params.source.type === "image") {
    layer.type = "image";
    layer.assetId = params.source.assetId;
  } else if (params.source.type === "procedural") {
    layer.type = "procedural";
  }

  return layer;
}

/** @deprecated Legacy migration adapter. Use createLayer instead. */
export const createUniversalLayer = createLayer;

/**
 * Creates a canonical Layer with a ProceduralSource.
 */
export function createProceduralLayer(
  sourceOrKind: ProceduralSource | BackgroundItemType,
  nameOrOptions?:
    | string
    | {
        id?: string;
        visible?: boolean;
        opacity?: number;
        blendMode?: BlendMode;
        effectStack?: EffectStack;
        transform?: Partial<LayerTransform>;
        fit?: "contain" | "cover";
        locked?: boolean;
        parameters?: Record<string, unknown>;
        seed?: number;
      },
  options?: {
    id?: string;
    visible?: boolean;
    opacity?: number;
    blendMode?: BlendMode;
    effectStack?: EffectStack;
    transform?: Partial<LayerTransform>;
    fit?: "contain" | "cover";
    locked?: boolean;
    parameters?: Record<string, unknown>;
    seed?: number;
  }
): Layer {
  const isSourceObj =
    typeof sourceOrKind === "object" &&
    sourceOrKind !== null &&
    (sourceOrKind as ProceduralSource).type === "procedural";
  const kind: BackgroundItemType = isSourceObj
    ? (sourceOrKind as ProceduralSource).kind
    : (sourceOrKind as BackgroundItemType);
  const resolvedName = typeof nameOrOptions === "string" ? nameOrOptions : undefined;
  const resolvedOpts =
    typeof nameOrOptions === "object" && nameOrOptions !== null
      ? nameOrOptions
      : options || {};
  const parameters = isSourceObj
    ? (sourceOrKind as ProceduralSource).parameters
    : resolvedOpts.parameters || {};
  const seed = isSourceObj ? (sourceOrKind as ProceduralSource).seed : resolvedOpts.seed;

  const source: ProceduralSource = {
    type: "procedural",
    kind,
    parameters: parameters ? { ...parameters } : {},
    seed,
  };

  return createLayer({
    id: resolvedOpts.id,
    name: resolvedName || `${kind.charAt(0).toUpperCase() + kind.slice(1)} Layer`,
    source,
    visible: resolvedOpts.visible,
    opacity: resolvedOpts.opacity,
    blendMode: resolvedOpts.blendMode,
    effectStack: resolvedOpts.effectStack,
    transform: resolvedOpts.transform,
    fit: resolvedOpts.fit,
    locked: resolvedOpts.locked,
  });
}

/**
 * Creates a single-tier Group container.
 */
export function createGroup(
  name: string,
  children: Layer[] = [],
  options?: {
    id?: string;
    visible?: boolean;
    locked?: boolean;
    collapsed?: boolean;
    opacity?: number;
    blendMode?: BlendMode;
    effectStack?: EffectStack;
    transform?: Partial<LayerTransform>;
  }
): Group {
  const now = Date.now();
  const rawTransform = options?.transform;
  const transform: LayerTransform = {
    x: rawTransform && Number.isFinite(rawTransform.x) ? rawTransform.x! : DEFAULT_LAYER_TRANSFORM.x,
    y: rawTransform && Number.isFinite(rawTransform.y) ? rawTransform.y! : DEFAULT_LAYER_TRANSFORM.y,
    scaleX: rawTransform && Number.isFinite(rawTransform.scaleX) ? Math.max(0.05, Math.min(20, rawTransform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
    scaleY: rawTransform && Number.isFinite(rawTransform.scaleY) ? Math.max(0.05, Math.min(20, rawTransform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
    rotation: rawTransform && Number.isFinite(rawTransform.rotation) ? rawTransform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
  };

  return {
    id: options?.id || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
      ? `group-${crypto.randomUUID()}`
      : `group-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`),
    name,
    children: [...children],
    visible: options?.visible ?? true,
    locked: options?.locked ?? false,
    collapsed: options?.collapsed ?? false,
    opacity: options?.opacity !== undefined ? Math.max(0, Math.min(1, options.opacity)) : 1.0,
    blendMode: options?.blendMode ?? "normal",
    effectStack: options?.effectStack ? [...options.effectStack] : [],
    transform,
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Synthesizes a new default Frame with a canonical backdrop Layer at index 0.
 */
export function createDefaultFrame(id?: string, name?: string): Frame {
  const now = Date.now();
  const baseBackdrop = createDefaultBackdropLayer();
  const frameId = id || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `frame-${now}`);
  return {
    id: frameId,
    name: name || "Frame 1",
    dimensions: { ...DEFAULT_FRAME_DIMENSIONS },
    items: [baseBackdrop],
    activeLayerId: baseBackdrop.id,
    createdAt: now,
    updatedAt: now,
  };
}

// ---------------------------------------------------------------------------
// Universal Composition Model Normalization & Migration
// ---------------------------------------------------------------------------

/**
 * Normalizes an individual Layer into one or more Universal Layers.
 *
 * In the Unified Composition Model:
 * 1. An ImageLayer (or legacy image record) maps to a single Layer with ImageSource(assetId).
 * 2. A legacy GenerativeLayer (with stackable backgrounds) expands into individual
 *    Layers with ProceduralSource, preserving visual order, parameters, blend modes,
 *    opacity, and visibility.
 * 3. An already-canonical Layer (with ImageSource or ProceduralSource)
 *    is returned cleanly without mutation or re-migration (idempotent).
 */
export function normalizeLayerToUniversal(layer: Layer | Record<string, unknown>): Layer[] {
  if (!layer || typeof layer !== "object") return [];

  const candidate = layer as Record<string, unknown>;
  const now = Date.now();

  // Case 1: Already canonical Layer with valid LayerSource
  // If the layer already has a canonical LayerSource (and does not contain an unexpanded multi-item legacy background stack)
  const hasMultipleLegacyBackgrounds =
    Array.isArray(candidate.backgrounds) && candidate.backgrounds.length > 1;

  if (candidate.source && !hasMultipleLegacyBackgrounds) {
    if (isImageSource(candidate.source) || (candidate.source as Record<string, unknown>).type === "image") {
      const rawSource = candidate.source as ImageSource;
      const assetId = (rawSource?.assetId || candidate.assetId || "") as string;
      const source: ImageSource = {
        type: "image",
        assetId,
      };

      const rawTransform = candidate.transform as Partial<LayerTransform> | undefined;
      const transform: LayerTransform = {
        x: rawTransform && Number.isFinite(rawTransform.x) ? rawTransform.x! : DEFAULT_LAYER_TRANSFORM.x,
        y: rawTransform && Number.isFinite(rawTransform.y) ? rawTransform.y! : DEFAULT_LAYER_TRANSFORM.y,
        scaleX: rawTransform && Number.isFinite(rawTransform.scaleX) ? Math.max(0.05, Math.min(20, rawTransform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
        scaleY: rawTransform && Number.isFinite(rawTransform.scaleY) ? Math.max(0.05, Math.min(20, rawTransform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
        rotation: rawTransform && Number.isFinite(rawTransform.rotation) ? rawTransform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
      };

      const imageLayer: ImageLayer = {
        id: (candidate.id as string) || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `img-${now}`),
        name: (candidate.name as string) || "Image Layer",
        visible: candidate.visible !== false,
        opacity: typeof candidate.opacity === "number" ? Math.max(0, Math.min(1, candidate.opacity as number)) : 1.0,
        blendMode: (candidate.blendMode as BlendMode) || "normal",
        effectStack: Array.isArray(candidate.effectStack) ? ([...candidate.effectStack] as EffectStack) : [],
        locked: Boolean(candidate.locked),
        type: "image",
        assetId,
        source,
        fit: (candidate.fit as "contain" | "cover") || "contain",
        transform,
        createdAt: (candidate.createdAt as number) || now,
        updatedAt: (candidate.updatedAt as number) || now,
      };

      return [imageLayer];
    }

    if (isProceduralSource(candidate.source) || (candidate.source as Record<string, unknown>).type === "procedural") {
      const procSource = candidate.source as ProceduralSource;
      const rawTransform = candidate.transform as Partial<LayerTransform> | undefined;
      const transform: LayerTransform = {
        x: rawTransform && Number.isFinite(rawTransform.x) ? rawTransform.x! : DEFAULT_LAYER_TRANSFORM.x,
        y: rawTransform && Number.isFinite(rawTransform.y) ? rawTransform.y! : DEFAULT_LAYER_TRANSFORM.y,
        scaleX: rawTransform && Number.isFinite(rawTransform.scaleX) ? Math.max(0.05, Math.min(20, rawTransform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
        scaleY: rawTransform && Number.isFinite(rawTransform.scaleY) ? Math.max(0.05, Math.min(20, rawTransform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
        rotation: rawTransform && Number.isFinite(rawTransform.rotation) ? rawTransform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
      };

      const procLayer: Layer = {
        id: (candidate.id as string) || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `proc-${now}`),
        name: (candidate.name as string) || (candidate.name === "Background" ? "Background" : `${procSource.kind.charAt(0).toUpperCase() + procSource.kind.slice(1)} Layer`),
        visible: candidate.visible !== false,
        opacity: typeof candidate.opacity === "number" ? Math.max(0, Math.min(1, candidate.opacity as number)) : 1.0,
        blendMode: (candidate.blendMode as BlendMode) || "normal",
        effectStack: Array.isArray(candidate.effectStack) ? ([...candidate.effectStack] as EffectStack) : [],
        locked: Boolean(candidate.locked),
        type: (candidate.type as "procedural" | "generative") || "procedural",
        source: {
          type: "procedural",
          kind: procSource.kind,
          parameters: { ...procSource.parameters },
          seed: procSource.seed,
        },
        fit: (candidate.fit as "contain" | "cover") || "contain",
        transform,
        createdAt: (candidate.createdAt as number) || now,
        updatedAt: (candidate.updatedAt as number) || now,
      };

      return [procLayer];
    }
  }

  // Case 2: Legacy GenerativeLayer (or any layer containing backgrounds stack)
  const isGenerative =
    candidate.type === "generative" ||
    Array.isArray(candidate.backgrounds) ||
    Boolean(candidate.backgroundConfig);

  if (isGenerative) {
    let bgItems: BackgroundItem[] = [];
    if (Array.isArray(candidate.backgrounds) && candidate.backgrounds.length > 0) {
      bgItems = candidate.backgrounds as BackgroundItem[];
    } else if (Array.isArray(candidate.sublayers) && candidate.sublayers.length > 0) {
      bgItems = candidate.sublayers as BackgroundItem[];
    } else if (candidate.backgroundConfig) {
      bgItems = normalizeLegacyBackgroundToBackgrounds(candidate.backgroundConfig as BackgroundState);
    }

    // If no background items were found, synthesize a default solid background preserving candidate.id and transparent visibility
    if (bgItems.length === 0) {
      const bgConfig = candidate.backgroundConfig as Partial<BackgroundState> | undefined;
      const isExplicitlyVisible = candidate.visible !== false && Boolean(bgConfig && bgConfig.visible !== false);
      bgItems = [
        {
          id: (candidate.id as string) || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `bg-${Date.now()}`),
          type: "solid",
          enabled: isExplicitlyVisible,
          opacity: typeof candidate.opacity === "number" ? (candidate.opacity as number) : 1.0,
          blendMode: (candidate.blendMode as BlendMode) || "normal",
          parameters: { color: "#000000" },
        },
      ];
    }

    const effectStack = Array.isArray(candidate.effectStack) ? (candidate.effectStack as EffectStack) : [];
    const layerLocked = Boolean(candidate.locked);

    return bgItems.map((item, index) => {
      const proceduralSource: ProceduralSource = {
        type: "procedural",
        kind: item.type,
        parameters: item.parameters ? { ...item.parameters } : {},
        seed: item.seed,
      };

      const layerId = item.id || (index === 0 && candidate.id ? (candidate.id as string) : (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `bg-${now}-${index}`));

      const procLayer: Layer = {
        id: layerId,
        name: item.name || `${item.type.charAt(0).toUpperCase() + item.type.slice(1)} Background`,
        visible: item.enabled ?? true,
        opacity: typeof item.opacity === "number" ? Math.max(0, Math.min(1, item.opacity)) : 1.0,
        blendMode: item.blendMode || "normal",
        // The top procedural layer inherits any effectStack on the legacy GenerativeLayer
        effectStack: index === bgItems.length - 1 ? [...effectStack] : [],
        locked: index === 0 ? layerLocked : false,
        type: "procedural",
        source: proceduralSource,
        transform: { ...DEFAULT_LAYER_TRANSFORM },
        createdAt: (candidate.createdAt as number) || now,
        updatedAt: (candidate.updatedAt as number) || now,
      };

      return procLayer;
    });
  }

  // Case 3: Legacy Image Layer (without source)
  const isImage =
    candidate.type === "image" ||
    typeof candidate.assetId === "string";

  if (isImage) {
    const assetId = (candidate.assetId || "") as string;
    const source: ImageSource = {
      type: "image",
      assetId,
    };

    const rawTransform = candidate.transform as Partial<LayerTransform> | undefined;
    const transform: LayerTransform = {
      x: rawTransform && Number.isFinite(rawTransform.x) ? rawTransform.x! : DEFAULT_LAYER_TRANSFORM.x,
      y: rawTransform && Number.isFinite(rawTransform.y) ? rawTransform.y! : DEFAULT_LAYER_TRANSFORM.y,
      scaleX: rawTransform && Number.isFinite(rawTransform.scaleX) ? Math.max(0.05, Math.min(20, rawTransform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
      scaleY: rawTransform && Number.isFinite(rawTransform.scaleY) ? Math.max(0.05, Math.min(20, rawTransform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
      rotation: rawTransform && Number.isFinite(rawTransform.rotation) ? rawTransform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
    };

    const imageLayer: ImageLayer = {
      id: (candidate.id as string) || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `img-${now}`),
      name: (candidate.name as string) || "Image Layer",
      visible: candidate.visible !== false,
      opacity: typeof candidate.opacity === "number" ? Math.max(0, Math.min(1, candidate.opacity as number)) : 1.0,
      blendMode: (candidate.blendMode as BlendMode) || "normal",
      effectStack: Array.isArray(candidate.effectStack) ? ([...candidate.effectStack] as EffectStack) : [],
      locked: Boolean(candidate.locked),
      type: "image",
      assetId,
      source,
      fit: (candidate.fit as "contain" | "cover") || "contain",
      transform,
      createdAt: (candidate.createdAt as number) || now,
      updatedAt: (candidate.updatedAt as number) || now,
    };

    return [imageLayer];
  }

  // Fallback: return candidate as-is if unrecognized
  return [candidate as unknown as Layer];
}

/**
 * Flattens all visual Layers from root composition items in bottom-to-top order.
 */
export function flattenItemsToLayers(items: (Layer | Group)[]): Layer[] {
  const result: Layer[] = [];
  for (const item of items) {
    if (isLayer(item)) {
      result.push(item);
    } else if (isGroup(item)) {
      for (const child of item.children) {
        result.push(child);
      }
    }
  }
  return result;
}

/**
 * @deprecated Legacy migration adapter. Canonical runtime preserves empty item lists without manufacturing content.
 */
export function normalizeBackdrop(items: (Layer | Group)[]): (Layer | Group)[] {
  return items;
}

/**
 * Normalizes a complete Frame into the Unified Composition Model (Canonical Model B).
 *
 * Guaranteed Invariants:
 * 1. Frame.items is the sole composition stack (Layer | Group)[].
 * 2. Frame.items represents the entire composition stack in bottom-to-top order. An intentionally empty composition (items = []) is fully valid and preserved.
 * 3. Group membership is strictly physical containment (Group.children: Layer[]).
 * 4. Nested groups are dissolved inline and their visibility/lock state materialized onto children.
 * 5. Empty groups are auto-pruned.
 * 6. activeLayerId is preserved or safely recovered.
 * 7. Idempotency: normalize(normalize(x)) produces an identical structure.
 */
export function normalizeFrameToUniversalModel(rawFrame: unknown): Frame {
  if (!rawFrame || typeof rawFrame !== "object") {
    return createDefaultFrame();
  }

  const raw = rawFrame as Record<string, unknown>;
  const now = Date.now();

  let items: (Layer | Group)[] = [];

  // Case 1: Raw input already has `items`
  if (Array.isArray(raw.items)) {
    for (const rawItem of raw.items) {
      if (!rawItem || typeof rawItem !== "object") continue;

      if (Array.isArray((rawItem as any).children)) {
        // Group container
        const rawGroup = rawItem as Record<string, unknown>;
        const normalizedChildren: Layer[] = [];

        for (const child of (rawGroup.children as any[])) {
          if (!child || typeof child !== "object") continue;
          if (Array.isArray(child.children)) {
            // Nested Group: dissolve inline and materialize state onto children
            const nestedGroup = child as Record<string, unknown>;
            const nestedVisible = nestedGroup.visible !== false;
            const nestedLocked = Boolean(nestedGroup.locked);
            for (const grandChild of (nestedGroup.children as any[])) {
              const normalizedGrandChildren = normalizeLayerToUniversal(grandChild);
              for (const gc of normalizedGrandChildren) {
                normalizedChildren.push({
                  ...gc,
                  visible: nestedVisible && gc.visible !== false,
                  locked: Boolean(nestedLocked || gc.locked),
                });
              }
            }
          } else {
            const normalized = normalizeLayerToUniversal(child);
            normalizedChildren.push(...normalized);
          }
        }

        // Only keep group if it has at least 1 child (auto-prune empty groups)
        if (normalizedChildren.length > 0) {
          const rawGroupTransform = rawGroup.transform as Partial<LayerTransform> | undefined;
          const groupTransform: LayerTransform = {
            x: rawGroupTransform && Number.isFinite(rawGroupTransform.x) ? rawGroupTransform.x! : DEFAULT_LAYER_TRANSFORM.x,
            y: rawGroupTransform && Number.isFinite(rawGroupTransform.y) ? rawGroupTransform.y! : DEFAULT_LAYER_TRANSFORM.y,
            scaleX: rawGroupTransform && Number.isFinite(rawGroupTransform.scaleX) ? Math.max(0.05, Math.min(20, rawGroupTransform.scaleX!)) : DEFAULT_LAYER_TRANSFORM.scaleX,
            scaleY: rawGroupTransform && Number.isFinite(rawGroupTransform.scaleY) ? Math.max(0.05, Math.min(20, rawGroupTransform.scaleY!)) : DEFAULT_LAYER_TRANSFORM.scaleY,
            rotation: rawGroupTransform && Number.isFinite(rawGroupTransform.rotation) ? rawGroupTransform.rotation! : DEFAULT_LAYER_TRANSFORM.rotation,
          };

          items.push({
            id: String(rawGroup.id || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? `group-${crypto.randomUUID()}` : `group-${now}`)),
            name: String(rawGroup.name || "Group"),
            children: normalizedChildren,
            visible: rawGroup.visible !== false,
            locked: Boolean(rawGroup.locked),
            collapsed: Boolean(rawGroup.collapsed),
            opacity: typeof rawGroup.opacity === "number" && !isNaN(rawGroup.opacity) ? Math.max(0, Math.min(1, rawGroup.opacity)) : 1.0,
            blendMode: (rawGroup.blendMode as BlendMode) || "normal",
            effectStack: Array.isArray(rawGroup.effectStack) ? (rawGroup.effectStack as EffectStack) : [],
            transform: groupTransform,
            createdAt: Number(rawGroup.createdAt) || now,
            updatedAt: Number(rawGroup.updatedAt) || now,
          });
        }
      } else {
        // Layer
        const normalized = normalizeLayerToUniversal(rawItem);
        items.push(...normalized);
      }
    }
  } else if (Array.isArray(raw.layers)) {
    // Case 2: Legacy Model A format with `layers` and optional `groups`
    const normalizedLayers = (raw.layers as any[]).flatMap((l) => normalizeLayerToUniversal(l));
    const legacyGroups = Array.isArray(raw.groups) ? (raw.groups as any[]) : [];
    const groupedLayerIdSet = new Set<string>();
    const groupMap = new Map<string, { group: any; children: Layer[]; minIndex: number }>();

    for (const g of legacyGroups) {
      if (!g || !Array.isArray(g.layerIds)) continue;
      const childLayers: Layer[] = [];
      let minIndex = Number.MAX_SAFE_INTEGER;
      for (let i = 0; i < normalizedLayers.length; i++) {
        const layer = normalizedLayers[i];
        if (g.layerIds.includes(layer.id) || (layer as any).groupId === g.id) {
          childLayers.push(layer);
          groupedLayerIdSet.add(layer.id);
          if (i < minIndex) minIndex = i;
        }
      }
      if (childLayers.length > 0) {
        groupMap.set(g.id, { group: g, children: childLayers, minIndex });
      }
    }

    const placedGroupIds = new Set<string>();
    for (let i = 0; i < normalizedLayers.length; i++) {
      const layer = normalizedLayers[i];
      for (const [gid, gData] of groupMap.entries()) {
        if (!placedGroupIds.has(gid) && gData.minIndex === i) {
          items.push({
            id: String(gData.group.id || `group-${now}`),
            name: String(gData.group.name || "Group"),
            children: gData.children,
            visible: gData.group.visible !== false,
            locked: Boolean(gData.group.locked),
            collapsed: Boolean(gData.group.collapsed),
            opacity: typeof gData.group.opacity === "number" ? Math.max(0, Math.min(1, gData.group.opacity)) : 1.0,
            blendMode: (gData.group.blendMode as BlendMode) || "normal",
            effectStack: Array.isArray(gData.group.effectStack) ? (gData.group.effectStack as EffectStack) : [],
            transform: gData.group.transform ? { ...DEFAULT_LAYER_TRANSFORM, ...gData.group.transform } : { ...DEFAULT_LAYER_TRANSFORM },
            createdAt: Number(gData.group.createdAt) || now,
            updatedAt: Number(gData.group.updatedAt) || now,
          });
          placedGroupIds.add(gid);
        }
      }

      if (!groupedLayerIdSet.has(layer.id)) {
        items.push(layer);
      }
    }

    for (const [gid, gData] of groupMap.entries()) {
      if (!placedGroupIds.has(gid)) {
        items.push({
          id: String(gData.group.id || `group-${now}`),
          name: String(gData.group.name || "Group"),
          children: gData.children,
          visible: gData.group.visible !== false,
          locked: Boolean(gData.group.locked),
          collapsed: Boolean(gData.group.collapsed),
          opacity: typeof gData.group.opacity === "number" ? Math.max(0, Math.min(1, gData.group.opacity)) : 1.0,
          blendMode: (gData.group.blendMode as BlendMode) || "normal",
          effectStack: Array.isArray(gData.group.effectStack) ? (gData.group.effectStack as EffectStack) : [],
          transform: gData.group.transform ? { ...DEFAULT_LAYER_TRANSFORM, ...gData.group.transform } : { ...DEFAULT_LAYER_TRANSFORM },
          createdAt: Number(gData.group.createdAt) || now,
          updatedAt: Number(gData.group.updatedAt) || now,
        });
        placedGroupIds.add(gid);
      }
    }
  }

  // Recover or preserve activeLayerId (supporting both Layer and Group IDs)
  let activeLayerId = typeof raw.activeLayerId === "string" ? raw.activeLayerId : null;
  const itemExists = items.some((item) => {
    if (item.id === activeLayerId) return true;
    if (isGroup(item)) {
      return item.children.some((c) => c.id === activeLayerId);
    }
    return false;
  });

  if (!itemExists) {
    const allFlattenedLayers = flattenItemsToLayers(items);
    if (allFlattenedLayers.length > 0) {
      activeLayerId = allFlattenedLayers[allFlattenedLayers.length - 1].id;
    } else if (items.length > 0) {
      activeLayerId = items[items.length - 1].id;
    } else {
      activeLayerId = null;
    }
  }

  const frameDimensions = (raw.dimensions as any) || DEFAULT_FRAME_DIMENSIONS;

  return {
    id: String(raw.id || (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function" ? crypto.randomUUID() : `frame-${now}`)),
    name: String(raw.name || "Frame 1"),
    dimensions: {
      width: Number(frameDimensions.width) || 1080,
      height: Number(frameDimensions.height) || 1080,
      presetId: frameDimensions.presetId ?? null,
    },
    items,
    activeLayerId: activeLayerId ?? (items[0] && isLayer(items[0]) ? items[0].id : null),
    createdAt: Number(raw.createdAt) || now,
    updatedAt: Number(raw.updatedAt) || now,
  };
}
