import { defineToolcraft } from "@/toolcraft/runtime";
import { appIdentity } from "./app-identity";

export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    sizing: { mode: "editable-output" },
    upload: true,
  },
  identity: appIdentity,
  persistence: {
    storage: "localStorage",
    key: "toolcraft:effectsio:state:v1",
    version: 1,
    include: ["canvas", "values", "panels"],
  },
  panels: {
    controls: {
      title: "Effects IO Lab",
      sections: [
        {
          id: "source-material",
          title: "Source Image",
          controls: {
            "source.image": {
              type: "fileDrop",
              target: "source.image",
              label: "Source Image",
              description: "Upload an image to apply custom visual effects.",
              assetKind: "image",
              multiple: false,
              defaultValue: [],
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Source image update re-renders canvas output.",
            },
          },
        },
        {
          id: "style-presets",
          title: "Style Preset",
          controls: {
            "preset.selected": {
              type: "select",
              target: "preset.selected",
              label: "Style Preset",
              description: "Choose a visual style preset to transform your image.",
              defaultValue: "chiwara-screen-print",
              options: [
                { label: "Chiwara Screen Print", value: "chiwara-screen-print" },
                { label: "Chiwara Blue/Cream", value: "chiwara-blue-cream" },
                { label: "Editorial Halftone", value: "editorial-halftone" },
                { label: "Vintage Newspaper", value: "vintage-newspaper" },
                { label: "Poster Print", value: "poster-print" },
                { label: "Black & White Editorial", value: "bw-editorial" },
                { label: "Custom Duotone", value: "custom-duotone" },
                { label: "Parcelra Brand", value: "parcelra-brand" },
                { label: "Custom Preset", value: "custom" },
              ],
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Selecting a preset instantly updates the visual style configuration.",
            },
          },
        },
        {
          id: "color-tuning",
          title: "Ink & Paper Colors",
          controls: {
            "colors.shadow": {
              type: "color",
              target: "colors.shadow",
              label: "Shadow / Ink 1",
              description: "Primary ink color mapped to dark tones.",
              defaultValue: "#8B1E0F",
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Controls color mapping curve for shadow tones.",
            },
            "colors.highlight": {
              type: "color",
              target: "colors.highlight",
              label: "Highlight / Ink 2",
              description: "Secondary ink color mapped to highlight tones.",
              defaultValue: "#E07A5F",
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Controls color mapping curve for highlight tones.",
            },
          },
        },
        {
          id: "background-section",
          title: "Background",
          controls: {
            "export.includeBackground": {
              type: "switch",
              target: "export.includeBackground",
              label: "Background",
              description: "Include background color in canvas export.",
              defaultValue: true,
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Toggles background rendering in export.",
            },
            "appearance.background": {
              type: "color",
              target: "appearance.background",
              label: "Background color",
              description: "Base canvas and paper background color.",
              defaultValue: "#F4F1DE",
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Sets base canvas background color.",
            },
          },
        },
        {
          id: "effect-toggles",
          title: "Effect Modules",
          layoutGroups: [
            {
              layout: "inline",
              columns: 2,
              controls: [
                "toggles.raster.enableHalftone",
                "toggles.raster.enablePosterize",
              ],
            },
            {
              layout: "inline",
              columns: 2,
              controls: [
                "toggles.texture.enableMisregistration",
                "toggles.texture.enableGrain",
              ],
            },
          ],
          controls: {
            "toggles.raster.enableHalftone": {
              type: "switch",
              target: "toggles.raster.enableHalftone",
              label: "Halftone",
              description: "Rasterize tones into publication dot halftone screen.",
              defaultValue: true,
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Toggles grid-based halftone dot calculation.",
            },
            "toggles.raster.enablePosterize": {
              type: "switch",
              target: "toggles.raster.enablePosterize",
              label: "Posterize",
              description: "Quantize continuous color tones into discrete levels.",
              defaultValue: true,
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Toggles color quantization pass.",
            },
            "toggles.texture.enableMisregistration": {
              type: "switch",
              target: "toggles.texture.enableMisregistration",
              label: "Ink Shift",
              description: "Simulate physical screen print ink layer offset and bleed.",
              defaultValue: true,
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Toggles shifted ink channel compositing pass.",
            },
            "toggles.texture.enableGrain": {
              type: "switch",
              target: "toggles.texture.enableGrain",
              label: "Film Grain",
              description: "Add paper texture and film grain noise overlay.",
              defaultValue: true,
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Toggles grain noise canvas overlay pass.",
            },
          },
        },
        {
          id: "fine-tuning",
          title: "Fine-Tuning Controls",
          controls: {
            "tuning.halftoneDotSize": {
              type: "slider",
              target: "tuning.halftoneDotSize",
              label: "Halftone Dot Size",
              description: "Grid scale for halftone dots.",
              min: 1,
              max: 20,
              step: 1,
              defaultValue: 4,
              sliderValueKind: "continuous",
              applicability: {
                mode: "conditional",
                all: [{ target: "toggles.raster.enableHalftone", equals: true }],
              },
              performanceRole: "responsiveness",
              performanceReason: "Adjusts dot radius and grid sampling resolution.",
            },
            "tuning.halftoneAngle": {
              type: "slider",
              target: "tuning.halftoneAngle",
              label: "Screen Angle (°)",
              description: "Rotation angle for halftone dot grid.",
              min: 0,
              max: 90,
              step: 5,
              defaultValue: 45,
              sliderValueKind: "continuous",
              applicability: {
                mode: "conditional",
                all: [{ target: "toggles.raster.enableHalftone", equals: true }],
              },
              performanceRole: "responsiveness",
              performanceReason: "Rotates halftone grid coordinate space.",
            },
            "tuning.misregistrationShift": {
              type: "slider",
              target: "tuning.misregistrationShift",
              label: "Ink Shift (px)",
              description: "Offset distance between screen print ink passes.",
              min: 0,
              max: 15,
              step: 1,
              defaultValue: 4,
              sliderValueKind: "continuous",
              applicability: {
                mode: "conditional",
                all: [{ target: "toggles.texture.enableMisregistration", equals: true }],
              },
              performanceRole: "responsiveness",
              performanceReason: "Sets pixel offset distance for ink misregistration pass.",
            },
            "tuning.grainIntensity": {
              type: "slider",
              target: "tuning.grainIntensity",
              label: "Grain Intensity",
              description: "Noise density for paper and film grain.",
              min: 0,
              max: 100,
              step: 5,
              defaultValue: 25,
              sliderValueKind: "continuous",
              applicability: {
                mode: "conditional",
                all: [{ target: "toggles.texture.enableGrain", equals: true }],
              },
              performanceRole: "responsiveness",
              performanceReason: "Controls noise opacity during texture overlay pass.",
            },
            "tuning.contrast": {
              type: "slider",
              target: "tuning.contrast",
              label: "Contrast Shift",
              description: "Adjust luminance contrast curve.",
              min: -100,
              max: 100,
              step: 5,
              defaultValue: 20,
              sliderValueKind: "continuous",
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Tunes input pixel contrast response curve.",
            },
          },
        },
        {
          id: "image-export",
          title: "Image Export",
          layoutGroups: [
            {
              layout: "inline",
              columns: 2,
              controls: ["export.image.format", "export.image.resolution"],
            },
          ],
          controls: {
            "export.image.format": {
              type: "select",
              target: "export.image.format",
              label: "Format",
              description: "Select output image encoding format.",
              defaultValue: "png",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Selects output image encoding format.",
            },
            "export.image.resolution": {
              type: "select",
              target: "export.image.resolution",
              label: "Resolution",
              description: "Sets resolution multiplier for image export.",
              defaultValue: "4k",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              applicability: { mode: "always" },
              performanceRole: "responsiveness",
              performanceReason: "Sets resolution multiplier for image export.",
            },
            "output.exportImage": {
              type: "panelActions",
              target: "output.exportImage",
              actions: [
                {
                  value: "exportImage",
                  label: "Export Image",
                  role: "export-image",
                },
              ],
              applicability: { mode: "always" },
            },
          },
        },
      ],
    },
  },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
