import { defineToolcraft } from "@/toolcraft/runtime";
import { appIdentity } from "./app-identity";
import { blackAndWhiteEffect } from "./effects/modules/black-and-white";
import { duotoneEffect } from "./effects/modules/duotone";
import { grainEffect } from "./effects/modules/grain";
import { halftoneEffect } from "./effects/modules/halftone";
import { posterizeEffect } from "./effects/modules/posterize";
import { screenPrintEffect } from "./effects/modules/screen-print";
import { vintageFilmEffect } from "./effects/modules/vintage-film";
import { PRESET_THUMBNAILS } from "./effects/preset-thumbnails";

export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    sizing: { mode: "editable-output" },
    upload: true,
  },
  identity: appIdentity,
  persistence: {
    include: ["canvas", "values", "panels"],
    key: "toolcraft:effectsio:state:v1",
    storage: "localStorage",
    version: 1,
  },
  panels: {
    controls: {
      sections: [
        {
          id: "source-material",
          title: "Image Library",
          controls: {
            "source.image": {
              accept: ".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp",
              applicability: { mode: "always" },
              assetKind: "image",
              defaultValue: [],
              description: "Upload, import, and manage source images in your project library.",
              label: "Image Library",
              multiple: true,
              performanceReason: "Loads selected source image onto the workspace canvas.",
              performanceRole: "responsiveness",
              target: "source.image",
              type: "fileDrop",
            },
          },
        },
        {
          id: "effects-gallery",
          title: "Creative Effects",
          controls: {
            "effect.selected": {
              applicability: { mode: "always" },
              defaultValue: "original",
              description: "Choose a visual effect preset to apply to the active image.",
              items: [
                {
                  alt: "Original (Unaltered photo)",
                  src: PRESET_THUMBNAILS.original,
                  value: "original",
                },
                {
                  alt: "Black & White (Monochrome)",
                  src: PRESET_THUMBNAILS["black-and-white"],
                  value: "black-and-white",
                },
                {
                  alt: "Duotone (Navy to Cyan)",
                  src: PRESET_THUMBNAILS.duotone,
                  value: "duotone",
                },
                {
                  alt: "Posterize (Color Quantization)",
                  src: PRESET_THUMBNAILS.posterize,
                  value: "posterize",
                },
                {
                  alt: "Film Grain (Noise Texture)",
                  src: PRESET_THUMBNAILS.grain,
                  value: "grain",
                },
                {
                  alt: "Halftone (Dot Matrix)",
                  src: PRESET_THUMBNAILS.halftone,
                  value: "halftone",
                },
                {
                  alt: "Screen Print (Serigraphy)",
                  src: PRESET_THUMBNAILS["screen-print"],
                  value: "screen-print",
                },
                {
                  alt: "Vintage Film (Analog Retro)",
                  src: PRESET_THUMBNAILS["vintage-film"],
                  value: "vintage-film",
                },
              ],
              label: "Select Effect",
              performanceReason: "Selects creative effect algorithm to apply to the active image.",
              performanceRole: "responsiveness",
              target: "effect.selected",
              type: "imagePicker",
            },
          },
        },
        {
          id: "effects-tonal",
          title: "Tonal & Monochrome Adjustments",
          controls: {
            "bw.contrast": {
              applicability: {
                all: [{ equals: "black-and-white", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (blackAndWhiteEffect.defaultParameters.contrast as number) ?? 1.2,
              description: "Monochrome luminance contrast balance.",
              label: "Monochrome contrast",
              max: 2.5,
              min: 0.5,
              performanceReason: "Adjusts monochrome tonal contrast curve.",
              performanceRole: "responsiveness",
              semanticGroup: "bw",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "bw.contrast",
              type: "slider",
            },
            "bw.warmth": {
              applicability: {
                all: [{ equals: "black-and-white", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (blackAndWhiteEffect.defaultParameters.warmth as number) ?? 0,
              description: "Warm (sepia) or cool (cyan) monochrome tone offset.",
              label: "Warmth",
              max: 50,
              min: -50,
              performanceReason: "Adjusts monochrome temperature tint offset.",
              performanceRole: "responsiveness",
              semanticGroup: "bw",
              sliderValueKind: "continuous",
              step: 1,
              target: "bw.warmth",
              type: "slider",
            },
            "duotone.shadowColor": {
              applicability: {
                all: [{ equals: "duotone", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (duotoneEffect.defaultParameters.shadowColor as string) ?? "#0f172a",
              description: "Color mapped to dark shadow tones.",
              label: "Shadow color",
              performanceReason: "Sets duotone shadow mapping color.",
              performanceRole: "responsiveness",
              semanticGroup: "duotone",
              target: "duotone.shadowColor",
              type: "color",
            },
            "duotone.highlightColor": {
              applicability: {
                all: [{ equals: "duotone", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (duotoneEffect.defaultParameters.highlightColor as string) ?? "#38bdf8",
              description: "Color mapped to bright highlight tones.",
              label: "Highlight color",
              performanceReason: "Sets duotone highlight mapping color.",
              performanceRole: "responsiveness",
              semanticGroup: "duotone",
              target: "duotone.highlightColor",
              type: "color",
            },
            "duotone.contrast": {
              applicability: {
                all: [{ equals: "duotone", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (duotoneEffect.defaultParameters.contrast as number) ?? 1.0,
              description: "Steepness of gradient transition curve.",
              label: "Duotone contrast",
              max: 2.0,
              min: 0.5,
              performanceReason: "Adjusts duotone gradient contrast curve.",
              performanceRole: "responsiveness",
              semanticGroup: "duotone",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "duotone.contrast",
              type: "slider",
            },
            "posterize.levels": {
              applicability: {
                all: [{ equals: "posterize", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (posterizeEffect.defaultParameters.levels as number) ?? 4,
              description: "Number of color steps per RGB channel.",
              label: "Color levels",
              max: 16,
              min: 2,
              performanceReason: "Adjusts channel quantization step count.",
              performanceRole: "responsiveness",
              semanticGroup: "posterize",
              sliderValueKind: "discrete",
              step: 1,
              target: "posterize.levels",
              type: "slider",
              variant: "discrete",
            },
            "grain.intensity": {
              applicability: {
                all: [{ equals: "grain", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (grainEffect.defaultParameters.intensity as number) ?? 35,
              description: "Film grain noise amplitude.",
              label: "Grain intensity",
              max: 100,
              min: 5,
              performanceReason: "Controls film grain noise amplitude.",
              performanceRole: "responsiveness",
              semanticGroup: "grain",
              sliderValueKind: "continuous",
              step: 1,
              target: "grain.intensity",
              type: "slider",
            },
            "tonal.reset": {
              actions: [
                {
                  label: "Reset Tonal Effect",
                  value: "resetTonalEffect",
                },
              ],
              applicability: {
                all: [
                  {
                    oneOf: ["black-and-white", "duotone", "posterize", "grain"],
                    target: "effect.selected",
                  },
                ],
                mode: "conditional",
              },
              description: "Reset parameters for active tonal effect to defaults.",
              label: "Reset",
              performanceReason: "Resets parameters for active tonal effect.",
              performanceRole: "responsiveness",
              semanticGroup: "actions",
              target: "tonal.reset",
              type: "actions",
            },
          },
        },
        {
          id: "effects-artistic",
          title: "Print & Film Adjustments",
          controls: {
            "halftone.dotSize": {
              applicability: {
                all: [{ equals: "halftone", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (halftoneEffect.defaultParameters.dotSize as number) ?? 6,
              description: "Diameter of printed halftone dots.",
              label: "Dot size",
              max: 24,
              min: 2,
              performanceReason: "Adjusts diameter of printed halftone dots.",
              performanceRole: "responsiveness",
              semanticGroup: "halftone",
              sliderValueKind: "continuous",
              step: 1,
              target: "halftone.dotSize",
              type: "slider",
            },
            "halftone.contrast": {
              applicability: {
                all: [{ equals: "halftone", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (halftoneEffect.defaultParameters.contrast as number) ?? 1.3,
              description: "Steepness of dot size contrast curve.",
              label: "Halftone contrast",
              max: 2.5,
              min: 0.5,
              performanceReason: "Adjusts dot size contrast curve.",
              performanceRole: "responsiveness",
              semanticGroup: "halftone",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "halftone.contrast",
              type: "slider",
            },
            "halftone.angle": {
              applicability: {
                all: [{ equals: "halftone", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (halftoneEffect.defaultParameters.angle as number) ?? 45,
              description: "Screen rotation angle in degrees.",
              label: "Pattern angle",
              max: 90,
              min: 0,
              performanceReason: "Sets halftone screen angle.",
              performanceRole: "responsiveness",
              semanticGroup: "halftone",
              sliderValueKind: "continuous",
              step: 1,
              target: "halftone.angle",
              type: "slider",
            },
            "halftone.density": {
              applicability: {
                all: [{ equals: "halftone", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (halftoneEffect.defaultParameters.density as number) ?? 1.0,
              description: "Density spacing multiplier of halftone grid cells.",
              label: "Halftone density",
              max: 2.0,
              min: 0.5,
              performanceReason: "Adjusts density spacing of halftone cells.",
              performanceRole: "responsiveness",
              semanticGroup: "halftone",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "halftone.density",
              type: "slider",
            },
            "halftone.brightness": {
              applicability: {
                all: [{ equals: "halftone", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (halftoneEffect.defaultParameters.brightness as number) ?? 0,
              description: "Luminance tone offset before dot sizing.",
              label: "Halftone brightness",
              max: 50,
              min: -50,
              performanceReason: "Adjusts brightness tone offset.",
              performanceRole: "responsiveness",
              semanticGroup: "halftone",
              sliderValueKind: "continuous",
              step: 1,
              target: "halftone.brightness",
              type: "slider",
            },
            "vintageFilm.grain": {
              applicability: {
                all: [{ equals: "vintage-film", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (vintageFilmEffect.defaultParameters.grain as number) ?? 30,
              description: "Organic analog film grain intensity.",
              label: "Film grain",
              max: 80,
              min: 0,
              performanceReason: "Adjusts vintage film grain intensity.",
              performanceRole: "responsiveness",
              semanticGroup: "vintage",
              sliderValueKind: "continuous",
              step: 1,
              target: "vintageFilm.grain",
              type: "slider",
            },
            "vintageFilm.fade": {
              applicability: {
                all: [{ equals: "vintage-film", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (vintageFilmEffect.defaultParameters.fade as number) ?? 25,
              description: "Lifted matte black floor level.",
              label: "Faded blacks",
              max: 60,
              min: 0,
              performanceReason: "Adjusts faded black floor level.",
              performanceRole: "responsiveness",
              semanticGroup: "vintage",
              sliderValueKind: "continuous",
              step: 1,
              target: "vintageFilm.fade",
              type: "slider",
            },
            "vintageFilm.contrast": {
              applicability: {
                all: [{ equals: "vintage-film", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (vintageFilmEffect.defaultParameters.contrast as number) ?? 1.1,
              description: "Film tonal contrast curve.",
              label: "Film contrast",
              max: 2.0,
              min: 0.5,
              performanceReason: "Adjusts vintage film tonal contrast.",
              performanceRole: "responsiveness",
              semanticGroup: "vintage",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "vintageFilm.contrast",
              type: "slider",
            },
            "vintageFilm.saturation": {
              applicability: {
                all: [{ equals: "vintage-film", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (vintageFilmEffect.defaultParameters.saturation as number) ?? 0.8,
              description: "Color saturation level.",
              label: "Film saturation",
              max: 2.0,
              min: 0.0,
              performanceReason: "Adjusts color saturation level.",
              performanceRole: "responsiveness",
              semanticGroup: "vintage",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "vintageFilm.saturation",
              type: "slider",
            },
            "vintageFilm.vignette": {
              applicability: {
                all: [{ equals: "vintage-film", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (vintageFilmEffect.defaultParameters.vignette as number) ?? 40,
              description: "Radial optical lens edge darkening.",
              label: "Vignette",
              max: 100,
              min: 0,
              performanceReason: "Adjusts lens edge darkening.",
              performanceRole: "responsiveness",
              semanticGroup: "vintage",
              sliderValueKind: "continuous",
              step: 1,
              target: "vintageFilm.vignette",
              type: "slider",
            },
          },
        },
        {
          id: "effects-screenprint",
          title: "Graphic & Plate Adjustments",
          controls: {
            "screenPrint.inkColor1": {
              applicability: {
                all: [{ equals: "screen-print", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (screenPrintEffect.defaultParameters.inkColor1 as string) ?? "#e11d48",
              description: "Primary screen ink color.",
              label: "Primary ink",
              performanceReason: "Sets primary screen ink color.",
              performanceRole: "responsiveness",
              semanticGroup: "screenprint",
              target: "screenPrint.inkColor1",
              type: "color",
            },
            "screenPrint.inkColor2": {
              applicability: {
                all: [{ equals: "screen-print", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (screenPrintEffect.defaultParameters.inkColor2 as string) ?? "#0284c7",
              description: "Secondary screen ink color.",
              label: "Secondary ink",
              performanceReason: "Sets secondary screen ink color.",
              performanceRole: "responsiveness",
              semanticGroup: "screenprint",
              target: "screenPrint.inkColor2",
              type: "color",
            },
            "screenPrint.inkDensity": {
              applicability: {
                all: [{ equals: "screen-print", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (screenPrintEffect.defaultParameters.inkDensity as number) ?? 1.0,
              description: "Ink saturation density.",
              label: "Ink density",
              max: 2.0,
              min: 0.5,
              performanceReason: "Adjusts screen ink saturation density.",
              performanceRole: "responsiveness",
              semanticGroup: "screenprint",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "screenPrint.inkDensity",
              type: "slider",
            },
            "screenPrint.halftoneSize": {
              applicability: {
                all: [{ equals: "screen-print", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (screenPrintEffect.defaultParameters.halftoneSize as number) ?? 8,
              description: "Halftone dot grid size.",
              label: "Halftone size",
              max: 20,
              min: 2,
              performanceReason: "Sets screen print halftone dot size.",
              performanceRole: "responsiveness",
              semanticGroup: "screenprint",
              sliderValueKind: "continuous",
              step: 1,
              target: "screenPrint.halftoneSize",
              type: "slider",
            },
            "screenPrint.grain": {
              applicability: {
                all: [{ equals: "screen-print", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (screenPrintEffect.defaultParameters.grain as number) ?? 20,
              description: "Paper and ink fiber noise texture.",
              label: "Ink texture grain",
              max: 60,
              min: 0,
              performanceReason: "Adjusts paper and ink fiber noise.",
              performanceRole: "responsiveness",
              semanticGroup: "screenprint",
              sliderValueKind: "continuous",
              step: 1,
              target: "screenPrint.grain",
              type: "slider",
            },
            "screenPrint.contrast": {
              applicability: {
                all: [{ equals: "screen-print", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (screenPrintEffect.defaultParameters.contrast as number) ?? 1.4,
              description: "Separation plate tonal contrast curve.",
              label: "Plate contrast",
              max: 2.5,
              min: 0.5,
              performanceReason: "Adjusts separation plate contrast.",
              performanceRole: "responsiveness",
              semanticGroup: "screenprint",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "screenPrint.contrast",
              type: "slider",
            },
            "screenPrint.registrationOffset": {
              applicability: {
                all: [{ equals: "screen-print", target: "effect.selected" }],
                mode: "conditional",
              },
              defaultValue: (screenPrintEffect.defaultParameters.registrationOffset as number) ?? 3,
              description: "Misaligned color registration offset in pixels.",
              label: "Registration offset",
              max: 12,
              min: 0,
              performanceReason: "Sets misaligned color registration offset.",
              performanceRole: "responsiveness",
              semanticGroup: "screenprint",
              sliderValueKind: "continuous",
              step: 1,
              target: "screenPrint.registrationOffset",
              type: "slider",
            },
            "screenPrint.reset": {
              actions: [
                {
                  label: "Reset Screen Print",
                  value: "resetScreenPrintEffect",
                },
              ],
              applicability: {
                all: [{ equals: "screen-print", target: "effect.selected" }],
                mode: "conditional",
              },
              description: "Reset parameters for screen print effect to defaults.",
              label: "Reset",
              performanceReason: "Resets parameters for screen print effect.",
              performanceRole: "responsiveness",
              semanticGroup: "actions",
              target: "screenPrint.reset",
              type: "actions",
            },
          },
        },
        {
          id: "background-section",
          title: "Background",
          controls: {
            "export.includeBackground": {
              applicability: { mode: "always" },
              defaultValue: true,
              description: "Include background fill in output image export.",
              label: "Background",
              performanceReason: "Toggles background color inclusion during export.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            "appearance.background": {
              applicability: { mode: "always" },
              defaultValue: "#121316",
              description: "Canvas workspace and paper background tint.",
              label: "Background color",
              performanceReason: "Sets workspace canvas background color.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
        },
        {
          id: "image-export",
          layoutGroups: [
            {
              columns: 2,
              controls: ["export.image.format", "export.image.resolution"],
              layout: "inline",
            },
          ],
          title: "Image Export",
          controls: {
            "export.image.format": {
              applicability: { mode: "always" },
              defaultValue: "png",
              description: "Select output image format.",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              performanceReason: "Sets export image format.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            "export.image.resolution": {
              applicability: { mode: "always" },
              defaultValue: "4k",
              description: "Select output image resolution.",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              performanceReason: "Sets export image resolution.",
              performanceRole: "responsiveness",
              target: "export.image.resolution",
              type: "select",
            },
            "output.exportImage": {
              actions: [
                {
                  label: "Export Image",
                  role: "export-image",
                  value: "exportImage",
                },
              ],
              applicability: { mode: "always" },
              target: "output.exportImage",
              type: "panelActions",
            },
          },
        },
      ],
      title: "EffectsIO Workstation",
    },
  },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
