import type {
  ToolcraftComponentAcceptance,
  ToolcraftControlSectionInventoryEntry,
  ToolcraftProductReadiness,
  ToolcraftTransferMode,
} from "./acceptance/types";
import { appSchema } from "./app-schema";

const starterPersistenceSlices =
  appSchema.persistence.storage === "localStorage"
    ? appSchema.persistence.include
    : [];

export const appTransferMode: ToolcraftTransferMode = {
  animationIntent: { mode: "none" },
  mode: "new-toolcraft-app",
};

export const appProductReadiness: ToolcraftProductReadiness = {
  exportIntent: {
    image: { mode: "toolcraft-default" },
    video: { mode: "not-requested" },
  },
  interactionOwnership: [],
  mode: "product",
  productName: "EffectsIO",
  productSummary: "Personal visual-effects laboratory and visual style preset workstation.",
  requestedBehavior:
    "Upload images, choose visual style presets, fine-tune halftone, screen print, ink, and grain parameters, preview live on canvas, and export treated image.",
  viewInteraction: {
    mode: "non-spatial",
    reason: "EffectsIO is a 2D image visual-effects workstation without 3D scene geometry.",
  },
};

export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName:
      "declares production reload coverage for the starter schema",
    browser: true,
    browserTestName:
      "browser: app restores exact canvas, values, and panel workspace slices after reload",
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable:
      "Canvas size and zoom, their runtime values, and the moved and collapsed Controls workspace remain visibly restored after a real browser reload.",
    fixture: "starter runtime persisted workspace",
    id: "persistence.reload",
    kind: "runtime",
    persistenceCoverage: "reload",
    persistenceSlices: starterPersistenceSlices,
    target: "canvas.size.width",
    userAction:
      "Edit Canvas width and zoom, move and collapse Controls, wait for persistence, and reload the page.",
  },
  {
    automated: true,
    automatedTestName: "toggles infinity canvas viewport mode and restores finite dimensions",
    browser: true,
    browserTestName: "browser: user toggles infinity canvas mode and verifies restoration",
    componentType: "switch",
    evidence: "viewport-side-effect",
    expectedObservable: "Infinity canvas mode toggles artboard clipping and size controls.",
    fixture: "infinity canvas toggle switch",
    id: "runtime.infinity-canvas",
    kind: "runtime",
    infinityCanvasCoverage: "mode-and-restoration",
    target: "canvas.infinity",
    userAction: "Toggle the Infinity canvas switch on and off in the Setup panel.",
  },
  {
    automated: true,
    automatedTestName: "exports scene-bounded high-resolution PNG image on infinity canvas",
    browser: true,
    browserTestName: "browser: user exports image and verifies infinity canvas scene bounds cropping",
    componentType: "panelActions",
    evidence: "exported-bytes",
    expectedObservable: "Exported PNG is cropped to scene bounds provided by composition.",
    fixture: "export image button",
    id: "runtime.export-image-bounds",
    kind: "runtime",
    infinityCanvasCoverage: "scene-bounds-image-export",
    target: "output.exportImage",
    userAction: "Click Export Image button while Infinity canvas is enabled.",
  },
  {
    automated: true,
    automatedTestName: "renders source image upload dropzone",
    browser: true,
    browserTestName: "browser: user uploads source image to apply visual treatments",
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable: "Uploaded image is processed and rendered onto canvas.",
    fixture: "source image file upload",
    id: "control.source-image",
    kind: "control",
    mediaLifecycleCoverage: ["upload", "remove", "reset", "rotate", "flip", "transform-output"],
    target: "source.image",
    userAction: "Upload a JPEG or PNG image into the Source Image file drop zone.",
  },
  {
    automated: true,
    automatedTestName: "updates preset parameter defaults on selection",
    browser: true,
    browserTestName: "browser: user selects a visual style preset from dropdown",
    componentType: "select",
    evidence: "rendered-pixels",
    expectedObservable: "Canvas updates immediately with the selected visual style treatment.",
    fixture: "style preset selection",
    id: "control.preset-selected",
    kind: "control",
    optionCoverage: [
      "chiwara-screen-print",
      "chiwara-blue-cream",
      "editorial-halftone",
      "vintage-newspaper",
      "poster-print",
      "bw-editorial",
      "custom-duotone",
      "parcelra-brand",
      "custom",
    ],
    target: "preset.selected",
    userAction: "Select a visual style preset option from the Style Preset dropdown menu.",
  },
  {
    automated: true,
    automatedTestName: "tints shadow and dark ink tones",
    browser: true,
    browserTestName: "browser: user changes shadow ink color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Canvas dark ink tones recolor to the chosen shadow color.",
    fixture: "shadow color picker",
    id: "control.colors-shadow",
    kind: "control",
    target: "colors.shadow",
    userAction: "Pick a dark shadow color using the Shadow / Ink 1 color control.",
  },
  {
    automated: true,
    automatedTestName: "tints highlight and secondary ink tones",
    browser: true,
    browserTestName: "browser: user changes highlight ink color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Canvas highlight ink tones recolor to the chosen highlight color.",
    fixture: "highlight color picker",
    id: "control.colors-highlight",
    kind: "control",
    target: "colors.highlight",
    userAction: "Pick a bright highlight color using the Highlight / Ink 2 color control.",
  },
  {
    automated: true,
    automatedTestName: "toggles background inclusion in export",
    backgroundOutputCoverage: [
      "preview-hidden-when-excluded",
      "image-transparent-when-excluded",
      "infinity-viewport-color-and-dependency",
    ],
    browser: true,
    browserTestName: "browser: user toggles background switch",
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Export background inclusion toggles.",
    fixture: "background switch",
    id: "control.export-include-background",
    kind: "control",
    target: "export.includeBackground",
    userAction: "Toggle the Background switch on or off in the Setup panel.",
  },
  {
    automated: true,
    automatedTestName: "sets canvas paper background tint",
    browser: true,
    browserTestName: "browser: user changes paper background color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Canvas paper background recolors to the chosen paper tint.",
    fixture: "paper background color picker",
    id: "control.appearance-background",
    kind: "control",
    target: "appearance.background",
    userAction: "Select a base canvas background color using the Background color picker.",
  },
  {
    automated: true,
    automatedTestName: "toggles dot halftone screen pass",
    browser: true,
    browserTestName: "browser: user switches halftone screen module",
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Halftone dot screen turns on and off on the output canvas.",
    fixture: "halftone screen switch",
    id: "control.toggles-enable-halftone",
    kind: "control",
    target: "toggles.raster.enableHalftone",
    userAction: "Toggle the Halftone module switch on or off.",
  },
  {
    automated: true,
    automatedTestName: "toggles color level posterization pass",
    browser: true,
    browserTestName: "browser: user switches posterization module",
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Color level quantization turns on and off on the output canvas.",
    fixture: "posterization switch",
    id: "control.toggles-enable-posterize",
    kind: "control",
    target: "toggles.raster.enablePosterize",
    userAction: "Toggle the Posterize module switch on or off.",
  },
  {
    automated: true,
    automatedTestName: "toggles ink misregistration shift pass",
    browser: true,
    browserTestName: "browser: user switches screen misregistration module",
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Ink layer offset shift turns on and off on the output canvas.",
    fixture: "misregistration switch",
    id: "control.toggles-enable-misregistration",
    kind: "control",
    target: "toggles.texture.enableMisregistration",
    userAction: "Toggle the Ink Shift module switch on or off.",
  },
  {
    automated: true,
    automatedTestName: "toggles paper and film grain overlay pass",
    browser: true,
    browserTestName: "browser: user switches grain noise module",
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Paper grain overlay turns on and off on the output canvas.",
    fixture: "grain noise switch",
    id: "control.toggles-enable-grain",
    kind: "control",
    target: "toggles.texture.enableGrain",
    userAction: "Toggle the Film Grain module switch on or off.",
  },
  {
    automated: true,
    automatedTestName: "adjusts halftone grid dot size",
    browser: true,
    browserTestName: "browser: user adjusts halftone dot size slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Halftone dot resolution grid rescales on the canvas.",
    fixture: "halftone dot size slider",
    id: "control.tuning-halftone-dot-size",
    kind: "control",
    target: "tuning.halftoneDotSize",
    userAction: "Drag the Halftone Dot Size slider to adjust the dot grid scale.",
  },
  {
    automated: true,
    automatedTestName: "adjusts halftone screen grid angle",
    browser: true,
    browserTestName: "browser: user adjusts screen angle slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Halftone screen dots rotate on the canvas.",
    fixture: "screen angle slider",
    id: "control.tuning-halftone-angle",
    kind: "control",
    target: "tuning.halftoneAngle",
    userAction: "Drag the Screen Angle slider to rotate the halftone screen angle.",
  },
  {
    automated: true,
    automatedTestName: "adjusts ink misregistration shift offset distance",
    browser: true,
    browserTestName: "browser: user adjusts ink shift slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Distance between shifted ink passes changes on the canvas.",
    fixture: "misregistration shift slider",
    id: "control.tuning-misregistration-shift",
    kind: "control",
    target: "tuning.misregistrationShift",
    userAction: "Drag the Ink Shift slider to adjust the ink layer offset distance.",
  },
  {
    automated: true,
    automatedTestName: "adjusts grain noise intensity opacity",
    browser: true,
    browserTestName: "browser: user adjusts grain intensity slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Paper and film noise density changes on the canvas.",
    fixture: "grain intensity slider",
    id: "control.tuning-grain-intensity",
    kind: "control",
    target: "tuning.grainIntensity",
    userAction: "Drag the Grain Intensity slider to adjust paper noise opacity.",
  },
  {
    automated: true,
    automatedTestName: "adjusts luminance contrast response curve",
    browser: true,
    browserTestName: "browser: user adjusts contrast shift slider",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Canvas output contrast increases or decreases.",
    fixture: "contrast slider",
    id: "control.tuning-contrast",
    kind: "control",
    target: "tuning.contrast",
    userAction: "Drag the Contrast Shift slider to adjust image luminance contrast.",
  },
  {
    automated: true,
    automatedTestName: "selects image export format",
    browser: true,
    browserTestName: "browser: user selects export format from dropdown",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Exported image matches selected encoding format.",
    fixture: "export format select",
    id: "control.export-image-format",
    kind: "control",
    optionCoverage: ["png", "jpg"],
    target: "export.image.format",
    userAction: "Select an export image format from the Format dropdown.",
  },
  {
    automated: true,
    automatedTestName: "selects image export resolution multiplier",
    browser: true,
    browserTestName: "browser: user selects export resolution multiplier",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Exported image dimensions scale by chosen multiplier.",
    fixture: "export resolution select",
    id: "control.export-image-resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Select an export image resolution from the Resolution dropdown.",
  },
  {
    actionCoverage: ["exportImage"],
    automated: true,
    automatedTestName: "triggers export image download action",
    browser: true,
    browserTestName: "browser: user clicks Export Image button",
    componentType: "panelActions",
    evidence: "exported-bytes",
    expectedObservable: "High-resolution image file downloads.",
    exportArtifactCoverage: "all-required-image-export-behavior",
    fixture: "export image button",
    id: "control.output-export-image",
    kind: "control",
    target: "output.exportImage",
    userAction: "Click the Export Image action button in the sticky footer.",
  },
];

export const appControlSectionInventory: readonly ToolcraftControlSectionInventoryEntry[] = [
  {
    id: "source-material",
    title: "Source Image",
    entity: "Source Image",
    entityId: "source-material",
    groupingReason: "Upload and select source images for visual style treatments.",
    targets: ["source.image"],
  },
  {
    id: "style-presets",
    title: "Style Preset",
    entity: "Style Preset",
    entityId: "style-presets",
    groupingReason: "Select curated visual style treatments and presets.",
    targets: ["preset.selected"],
  },
  {
    id: "color-tuning",
    title: "Ink & Paper Colors",
    entity: "Ink & Paper Colors",
    entityId: "color-tuning",
    groupingReason: "Adjust primary ink channels and paper background tints.",
    targets: ["colors.shadow", "colors.highlight"],
  },
  {
    id: "background-section",
    title: "Background",
    entity: "Background",
    entityId: "background-section",
    groupingReason: "Configure background color and export background transparency.",
    targets: ["export.includeBackground", "appearance.background"],
  },
  {
    id: "effect-toggles",
    title: "Effect Modules",
    entity: "toggles",
    entityId: "effect-toggles",
    groupingReason: "Enable or disable individual effect pipeline stages.",
    targets: [
      "toggles.raster.enableHalftone",
      "toggles.raster.enablePosterize",
      "toggles.texture.enableMisregistration",
      "toggles.texture.enableGrain",
    ],
  },
  {
    id: "fine-tuning",
    title: "Fine-Tuning Controls",
    entity: "Fine-Tuning Controls",
    entityId: "fine-tuning",
    groupingReason: "Fine-tune dot size, angle, shift, grain, and contrast parameters.",
    targets: [
      "tuning.halftoneDotSize",
      "tuning.halftoneAngle",
      "tuning.misregistrationShift",
      "tuning.grainIntensity",
      "tuning.contrast",
    ],
  },
  {
    id: "image-export.part-export-image-format-1k2loow",
    title: "Image Export",
    entity: "Image Export",
    entityId: "image-export.part-export-image-format-1k2loow",
    groupingReason: "Configure export image format and resolution.",
    targets: ["export.image.format", "export.image.resolution"],
  },
];
