import { defineToolcraft } from "@/toolcraft/runtime";
import { appIdentity } from "./app-identity";
import { PRESET_THUMBNAILS } from "./effects/preset-thumbnails";

export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    sizing: { mode: "editable-output" },
    upload: true,
  },
  identity: appIdentity,
  persistence: {
    include: ["canvas", "values", "panels"],
    key: "toolcraft:effectsio:state:v1",
    storage: "localStorage",
    version: 1,
  },
  panels: {
    controls: {
      sections: [
        {
          id: "source-material",
          title: "Image Library",
          controls: {
            "source.image": {
              accept: ".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp",
              applicability: { mode: "always" },
              assetKind: "image",
              defaultValue: [],
              description: "Upload, import, and manage source images in your project library.",
              label: "Image Library",
              multiple: true,
              performanceReason: "Loads selected source image onto the workspace canvas.",
              performanceRole: "responsiveness",
              target: "source.image",
              type: "fileDrop",
            },
          },
        },
        {
          id: "effects-section",
          title: "Creative Effects",
          controls: {
            "effect.tab": {
              applicability: { mode: "always" },
              defaultValue: "gallery",
              description: "Switch between effects gallery and fine-tuning parameter adjustments.",
              label: "Mode",
              options: [
                { label: "Gallery", value: "gallery" },
                { label: "Controls", value: "controls" },
              ],
              performanceReason: "Switches effects panel view between gallery and parameter adjustments.",
              performanceRole: "responsiveness",
              semanticGroup: "mode",
              target: "effect.tab",
              type: "tabs",
            },
            "effect.selected": {
              applicability: {
                all: [{ equals: "gallery", target: "effect.tab" }],
                mode: "conditional",
              },
              defaultValue: "original",
              description: "Choose a visual effect to apply to the active image.",
              items: [
                {
                  alt: "Original (Unaltered photo)",
                  src: PRESET_THUMBNAILS.original,
                  value: "original",
                },
                {
                  alt: "Black & White (Monochrome)",
                  src: PRESET_THUMBNAILS["black-and-white"],
                  value: "black-and-white",
                },
                {
                  alt: "Duotone (Navy to Cyan)",
                  src: PRESET_THUMBNAILS.duotone,
                  value: "duotone",
                },
                {
                  alt: "Posterize (Color Quantization)",
                  src: PRESET_THUMBNAILS.posterize,
                  value: "posterize",
                },
                {
                  alt: "Film Grain (Noise Texture)",
                  src: PRESET_THUMBNAILS.grain,
                  value: "grain",
                },
              ],
              label: "Select Effect",
              performanceReason: "Selects creative effect algorithm to apply to the active image.",
              performanceRole: "responsiveness",
              semanticGroup: "selection",
              target: "effect.selected",
              type: "imagePicker",
            },
            "effect.bw.contrast": {
              applicability: {
                all: [
                  { equals: "controls", target: "effect.tab" },
                  { equals: "black-and-white", target: "effect.selected" },
                ],
                mode: "conditional",
              },
              defaultValue: 1.2,
              description: "Adjust monochrome contrast balance.",
              label: "Contrast",
              max: 2.5,
              min: 0.5,
              performanceReason: "Tunes black and white contrast curve.",
              performanceRole: "responsiveness",
              semanticGroup: "black-and-white",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "effect.bw.contrast",
              type: "slider",
            },
            "effect.bw.warmth": {
              applicability: {
                all: [
                  { equals: "controls", target: "effect.tab" },
                  { equals: "black-and-white", target: "effect.selected" },
                ],
                mode: "conditional",
              },
              defaultValue: 0,
              description: "Adjust tone warmth offset.",
              label: "Warmth",
              max: 50,
              min: -50,
              performanceReason: "Adjusts tone temperature offset for monochrome conversion.",
              performanceRole: "responsiveness",
              semanticGroup: "black-and-white",
              sliderValueKind: "continuous",
              step: 1,
              target: "effect.bw.warmth",
              type: "slider",
            },
            "effect.duotone.shadowColor": {
              applicability: {
                all: [
                  { equals: "controls", target: "effect.tab" },
                  { equals: "duotone", target: "effect.selected" },
                ],
                mode: "conditional",
              },
              defaultValue: "#0f172a",
              description: "Color mapped to dark shadow tones.",
              label: "Shadow color",
              performanceReason: "Sets duotone shadow mapping color.",
              performanceRole: "responsiveness",
              semanticGroup: "duotone",
              target: "effect.duotone.shadowColor",
              type: "color",
            },
            "effect.duotone.highlightColor": {
              applicability: {
                all: [
                  { equals: "controls", target: "effect.tab" },
                  { equals: "duotone", target: "effect.selected" },
                ],
                mode: "conditional",
              },
              defaultValue: "#38bdf8",
              description: "Color mapped to bright highlight tones.",
              label: "Highlight color",
              performanceReason: "Sets duotone highlight mapping color.",
              performanceRole: "responsiveness",
              semanticGroup: "duotone",
              target: "effect.duotone.highlightColor",
              type: "color",
            },
            "effect.posterize.levels": {
              applicability: {
                all: [
                  { equals: "controls", target: "effect.tab" },
                  { equals: "posterize", target: "effect.selected" },
                ],
                mode: "conditional",
              },
              defaultValue: 4,
              description: "Number of color steps per RGB channel.",
              label: "Color levels",
              max: 16,
              min: 2,
              performanceReason: "Adjusts channel quantization step count.",
              performanceRole: "responsiveness",
              semanticGroup: "posterize",
              sliderValueKind: "discrete",
              step: 1,
              target: "effect.posterize.levels",
              type: "slider",
              variant: "discrete",
            },
            "effect.posterize.saturation": {
              applicability: {
                all: [
                  { equals: "controls", target: "effect.tab" },
                  { equals: "posterize", target: "effect.selected" },
                ],
                mode: "conditional",
              },
              defaultValue: 1.0,
              description: "Pre-quantization color saturation multiplier.",
              label: "Saturation",
              max: 2.0,
              min: 0.5,
              performanceReason: "Tunes saturation multiplier before color quantization.",
              performanceRole: "responsiveness",
              semanticGroup: "posterize",
              sliderValueKind: "continuous",
              step: 0.1,
              target: "effect.posterize.saturation",
              type: "slider",
            },
            "effect.grain.intensity": {
              applicability: {
                all: [
                  { equals: "controls", target: "effect.tab" },
                  { equals: "grain", target: "effect.selected" },
                ],
                mode: "conditional",
              },
              defaultValue: 35,
              description: "Film grain noise amplitude.",
              label: "Intensity",
              max: 100,
              min: 5,
              performanceReason: "Controls film grain noise amplitude.",
              performanceRole: "responsiveness",
              semanticGroup: "grain",
              sliderValueKind: "continuous",
              step: 1,
              target: "effect.grain.intensity",
              type: "slider",
            },
            "effect.grain.size": {
              applicability: {
                all: [
                  { equals: "controls", target: "effect.tab" },
                  { equals: "grain", target: "effect.selected" },
                ],
                mode: "conditional",
              },
              defaultValue: 1,
              description: "Grain particle cluster block size.",
              label: "Particle size",
              max: 4,
              min: 1,
              performanceReason: "Controls film grain particle scaling block size.",
              performanceRole: "responsiveness",
              semanticGroup: "grain",
              sliderValueKind: "discrete",
              step: 1,
              target: "effect.grain.size",
              type: "slider",
              variant: "discrete",
            },
          },
        },
        {
          id: "background-section",
          title: "Background",
          controls: {
            "export.includeBackground": {
              applicability: { mode: "always" },
              defaultValue: true,
              description: "Include background fill in output image export.",
              label: "Background",
              performanceReason: "Toggles background color inclusion during export.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            "appearance.background": {
              applicability: { mode: "always" },
              defaultValue: "#121316",
              description: "Canvas workspace and paper background tint.",
              label: "Background color",
              performanceReason: "Sets workspace canvas background color.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
        },
        {
          id: "image-export",
          layoutGroups: [
            {
              columns: 2,
              controls: ["export.image.format", "export.image.resolution"],
              layout: "inline",
            },
          ],
          title: "Image Export",
          controls: {
            "export.image.format": {
              applicability: { mode: "always" },
              defaultValue: "png",
              description: "Select output image format.",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              performanceReason: "Sets export image format.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            "export.image.resolution": {
              applicability: { mode: "always" },
              defaultValue: "4k",
              description: "Select output image resolution.",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              performanceReason: "Sets export image resolution.",
              performanceRole: "responsiveness",
              target: "export.image.resolution",
              type: "select",
            },
            "output.exportImage": {
              actions: [
                {
                  label: "Export Image",
                  role: "export-image",
                  value: "exportImage",
                },
              ],
              applicability: { mode: "always" },
              target: "output.exportImage",
              type: "panelActions",
            },
          },
        },
      ],
      title: "EffectsIO Workstation",
    },
  },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
