import type {
  ToolcraftComponentAcceptance,
  ToolcraftControlSectionInventoryEntry,
  ToolcraftProductReadiness,
  ToolcraftTransferMode,
} from "./acceptance/types";
import { appSchema } from "./app-schema";

const starterPersistenceSlices =
  appSchema.persistence.storage === "localStorage"
    ? appSchema.persistence.include
    : [];

export const appTransferMode: ToolcraftTransferMode = {
  animationIntent: { mode: "none" },
  mode: "new-toolcraft-app",
};

export const appProductReadiness: ToolcraftProductReadiness = {
  exportIntent: {
    image: { mode: "toolcraft-default" },
    video: { mode: "not-requested" },
  },
  interactionOwnership: [],
  mode: "product",
  productName: "EffectsIO",
  productSummary: "A personal image effects and visual-style workstation for applying repeatable creative treatments to images.",
  requestedBehavior:
    "Upload single or multiple images into the Image Library, select active or batch image sets, reorder, rotate, flip, preview active image on canvas with zoom/pan/center/undo/redo, and export images.",
  viewInteraction: {
    mode: "non-spatial",
    reason: "EffectsIO is a 2D image workstation without 3D scene geometry.",
  },
};

export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName:
      "declares production reload coverage for the starter schema",
    browser: true,
    browserTestName:
      "browser: app restores exact canvas, values, and panel workspace slices after reload",
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable:
      "Canvas size and zoom, their runtime values, and the moved and collapsed Controls workspace remain visibly restored after a real browser reload.",
    fixture: "starter runtime persisted workspace",
    id: "persistence.reload",
    kind: "runtime",
    persistenceCoverage: "reload",
    persistenceSlices: starterPersistenceSlices,
    target: "canvas.size.width",
    userAction:
      "Edit Canvas width and zoom, move and collapse Controls, wait for persistence, and reload the page.",
  },
  {
    automated: true,
    automatedTestName: "toggles infinity canvas viewport mode and restores finite dimensions",
    browser: true,
    browserTestName: "browser: user toggles infinity canvas mode and verifies restoration",
    componentType: "switch",
    evidence: "viewport-side-effect",
    expectedObservable: "Infinity canvas mode toggles artboard clipping and size controls.",
    fixture: "infinity canvas toggle switch",
    id: "runtime.infinity-canvas",
    kind: "runtime",
    infinityCanvasCoverage: "mode-and-restoration",
    target: "canvas.infinity",
    userAction: "Toggle the Infinity canvas switch on and off in the Setup panel.",
  },
  {
    automated: true,
    automatedTestName: "exports scene-bounded high-resolution PNG image on infinity canvas",
    browser: true,
    browserTestName: "browser: user exports image and verifies infinity canvas scene bounds cropping",
    componentType: "panelActions",
    evidence: "exported-bytes",
    expectedObservable: "Exported PNG is cropped to scene bounds provided by composition.",
    fixture: "export image button",
    id: "runtime.export-image-bounds",
    kind: "runtime",
    infinityCanvasCoverage: "scene-bounds-image-export",
    target: "output.exportImage",
    userAction: "Click Export Image button while Infinity canvas is enabled.",
  },
  {
    automated: true,
    automatedTestName: "renders multi-image library file dropzone",
    browser: true,
    browserTestName: "browser: user uploads multiple source images into image library",
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable: "Uploaded images render in sortable thumbnail library grid.",
    fixture: "multi-image file upload",
    id: "control.source-image",
    kind: "control",
    mediaLifecycleCoverage: ["upload", "remove", "reset", "reorder", "order-output", "rotate", "flip", "transform-output"],
    target: "source.image",
    userAction: "Upload single or multiple JPEG, PNG, or WEBP images into the Image Library file drop zone.",
  },
  {
    automated: true,
    automatedTestName: "switches active image in workstation canvas",
    browser: true,
    browserTestName: "browser: user selects active image thumbnail",
    componentType: "select",
    evidence: "rendered-pixels",
    expectedObservable: "Canvas updates immediately to show selected active image.",
    fixture: "active image selection thumbnail grid",
    id: "control.source-active-image",
    kind: "control",
    optionCoverage: [],
    target: "source.activeImage",
    userAction: "Click an image thumbnail in the Image Library to set the active canvas image.",
  },
  {
    automated: true,
    automatedTestName: "toggles background inclusion in export",
    backgroundOutputCoverage: [
      "preview-hidden-when-excluded",
      "image-transparent-when-excluded",
      "infinity-viewport-color-and-dependency",
    ],
    browser: true,
    browserTestName: "browser: user toggles background switch",
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Export background inclusion toggles.",
    fixture: "background switch",
    id: "control.export-include-background",
    kind: "control",
    target: "export.includeBackground",
    userAction: "Toggle the Background switch on or off in the Setup panel.",
  },
  {
    automated: true,
    automatedTestName: "sets canvas paper background tint",
    browser: true,
    browserTestName: "browser: user changes paper background color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Canvas paper background recolors to the chosen paper tint.",
    fixture: "paper background color picker",
    id: "control.appearance-background",
    kind: "control",
    target: "appearance.background",
    userAction: "Select a base canvas background color using the Background color picker.",
  },
  {
    automated: true,
    automatedTestName: "selects image export format",
    browser: true,
    browserTestName: "browser: user selects export format from dropdown",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Exported image matches selected encoding format.",
    fixture: "export format select",
    id: "control.export-image-format",
    kind: "control",
    optionCoverage: ["png", "jpg"],
    target: "export.image.format",
    userAction: "Select an export image format from the Format dropdown.",
  },
  {
    automated: true,
    automatedTestName: "selects image export resolution multiplier",
    browser: true,
    browserTestName: "browser: user selects export resolution multiplier",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Exported image dimensions scale by chosen multiplier.",
    fixture: "export resolution select",
    id: "control.export-image-resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Select an export image resolution from the Resolution dropdown.",
  },
  {
    actionCoverage: ["exportImage"],
    automated: true,
    automatedTestName: "triggers export image download action",
    browser: true,
    browserTestName: "browser: user clicks Export Image button",
    componentType: "panelActions",
    evidence: "exported-bytes",
    expectedObservable: "High-resolution image file downloads.",
    exportArtifactCoverage: "all-required-image-export-behavior",
    fixture: "export image button",
    id: "control.output-export-image",
    kind: "control",
    target: "output.exportImage",
    userAction: "Click the Export Image action button in the sticky footer.",
  },
];

export const appControlSectionInventory: readonly ToolcraftControlSectionInventoryEntry[] = [
  {
    id: "source-material",
    title: "Image Library",
    entity: "Image Library",
    entityId: "source-material",
    groupingReason: "Upload and manage source images in your image library.",
    targets: ["source.image"],
  },
  {
    id: "active-selection",
    title: "Active Selection",
    entity: "Active Selection",
    entityId: "active-selection",
    groupingReason: "Select active image in image library.",
    targets: ["source.activeImage"],
  },
  {
    id: "background-section",
    title: "Background",
    entity: "Background",
    entityId: "background-section",
    groupingReason: "Configure background color and export background transparency.",
    targets: ["export.includeBackground", "appearance.background"],
  },
  {
    id: "image-export.part-export-image-format-1k2loow",
    title: "Image Export",
    entity: "Image Export",
    entityId: "image-export.part-export-image-format-1k2loow",
    groupingReason: "Configure export image format and resolution.",
    targets: ["export.image.format", "export.image.resolution"],
  },
];
