import type {
  ToolcraftComponentAcceptance,
  ToolcraftControlSectionInventoryEntry,
  ToolcraftProductReadiness,
  ToolcraftTransferMode,
} from "./acceptance/types";
import { appSchema } from "./app-schema";

const starterPersistenceSlices =
  appSchema.persistence.storage === "localStorage"
    ? appSchema.persistence.include
    : [];

export const appTransferMode: ToolcraftTransferMode = {
  animationIntent: { mode: "none" },
  mode: "new-toolcraft-app",
};

export const appProductReadiness: ToolcraftProductReadiness = {
  exportIntent: {
    image: { mode: "toolcraft-default" },
    video: { mode: "not-requested" },
  },
  interactionOwnership: [
    {
      alternative: {
        reason:
          "Canvas selection would duplicate the Image Library collection workflow and its upload, delete, and transform actions.",
        surface: "canvas",
      },
      capability: "structured-selection",
      evidence: {
        detail:
          "The requested workflow explicitly uses the Image Library thumbnail grid as the image-selection mechanism.",
        source: "user-request",
      },
      id: "image-library-selection",
      reason:
        "The panel keeps image upload, thumbnail selection, and image-specific actions together in one discoverable collection workflow.",
      surface: "panel",
      target: "source.image",
    },
  ],
  mode: "product",
  productName: "EffectsIO",
  productSummary: "A personal image effects and visual-style workstation for applying repeatable creative treatments to images.",
  requestedBehavior:
    "Upload single or multiple images into the Image Library, select active image, apply creative effects from the effect gallery (Original, Black & White, Duotone, Posterize, Grain), preview on canvas with zoom/pan/center/undo/redo, and export images.",
  viewInteraction: {
    mode: "non-spatial",
    reason: "EffectsIO is a 2D image workstation without 3D scene geometry.",
  },
};

export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName:
      "declares production reload coverage for the starter schema",
    browser: true,
    browserTestName:
      "browser: app restores exact canvas, values, and panel workspace slices after reload",
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable:
      "Canvas size and zoom, their runtime values, and the moved and collapsed Controls workspace remain visibly restored after a real browser reload.",
    fixture: "starter runtime persisted workspace",
    id: "persistence.reload",
    kind: "runtime",
    persistenceCoverage: "reload",
    persistenceSlices: starterPersistenceSlices,
    target: "canvas.size.width",
    userAction:
      "Edit Canvas width and zoom, move and collapse Controls, wait for persistence, and reload the page.",
  },
  {
    automated: true,
    automatedTestName: "toggles infinity canvas viewport mode and restores finite dimensions",
    browser: true,
    browserTestName: "browser: user toggles infinity canvas mode and verifies restoration",
    componentType: "switch",
    evidence: "viewport-side-effect",
    expectedObservable: "Infinity canvas mode toggles artboard clipping and size controls.",
    fixture: "infinity canvas toggle switch",
    id: "runtime.infinity-canvas",
    kind: "runtime",
    infinityCanvasCoverage: "mode-and-restoration",
    target: "canvas.infinity",
    userAction: "Toggle the Infinity canvas switch on and off in the Setup panel.",
  },
  {
    automated: true,
    automatedTestName: "exports scene-bounded high-resolution PNG image on infinity canvas",
    browser: true,
    browserTestName: "browser: user exports image and verifies infinity canvas scene bounds cropping",
    componentType: "panelActions",
    evidence: "exported-bytes",
    expectedObservable: "Exported PNG is cropped to scene bounds provided by composition.",
    fixture: "export image button",
    id: "runtime.export-image-bounds",
    kind: "runtime",
    infinityCanvasCoverage: "scene-bounds-image-export",
    target: "output.exportImage",
    userAction: "Click Export Image button while Infinity canvas is enabled.",
  },
  {
    automated: true,
    automatedTestName: "switches active panel view between effects and library",
    browser: true,
    browserTestName: "browser: user toggles between effects and library tabs",
    componentType: "tabs",
    evidence: "command-side-effect",
    expectedObservable: "Active panel view switches between Creative Effects and Image Library sections.",
    fixture: "workspace view switcher tabs",
    id: "control.panel-active-view",
    kind: "control",
    optionCoverage: ["effects", "library"],
    target: "panel.activeView",
    userAction: "Click the Effects or Library & Controls tab in the controls panel.",
  },
  {
    automated: true,
    automatedTestName: "selects creative effect to apply to canvas image",
    browser: true,
    browserTestName: "browser: user selects effect from creative effects grid",
    componentType: "imagePicker",
    evidence: "rendered-pixels",
    expectedObservable: "Selected effect algorithm transforms the active image rendered on the canvas.",
    fixture: "effect image picker grid",
    id: "control.effect-selected",
    kind: "control",
    optionCoverage: ["original", "black-and-white", "duotone", "posterize", "grain"],
    target: "effect.selected",
    userAction: "Select an effect thumbnail in the Creative Effects grid.",
  },
  {
    automated: true,
    automatedTestName: "renders multi-image library file dropzone",
    browser: true,
    browserTestName: "browser: user uploads multiple source images into image library",
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable: "Uploaded images render in the thumbnail grid, and selecting a thumbnail switches the canvas to that image.",
    fixture: "multi-image file upload",
    id: "control.source-image",
    interactionId: "image-library-selection",
    kind: "control",
    mediaLifecycleCoverage: ["upload", "remove", "reset", "reorder", "order-output", "rotate", "flip", "transform-output"],
    target: "source.image",
    userAction: "Upload single or multiple JPEG, PNG, or WEBP images into the Image Library file drop zone.",
  },
  {
    automated: true,
    automatedTestName: "toggles background inclusion in export",
    backgroundOutputCoverage: [
      "preview-hidden-when-excluded",
      "image-transparent-when-excluded",
      "infinity-viewport-color-and-dependency",
    ],
    browser: true,
    browserTestName: "browser: user toggles background switch",
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Export background inclusion toggles.",
    fixture: "background switch",
    id: "control.export-include-background",
    kind: "control",
    target: "export.includeBackground",
    userAction: "Toggle the Background switch on or off in the Setup panel.",
  },
  {
    automated: true,
    automatedTestName: "sets canvas paper background tint",
    browser: true,
    browserTestName: "browser: user changes paper background color picker",
    componentType: "color",
    evidence: "rendered-pixels",
    expectedObservable: "Canvas paper background recolors to the chosen paper tint.",
    fixture: "paper background color picker",
    id: "control.appearance-background",
    kind: "control",
    target: "appearance.background",
    userAction: "Select a base canvas background color using the Background color picker.",
  },
  {
    automated: true,
    automatedTestName: "selects image export format",
    browser: true,
    browserTestName: "browser: user selects export format from dropdown",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Exported image matches selected encoding format.",
    fixture: "export format select",
    id: "control.export-image-format",
    kind: "control",
    optionCoverage: ["png", "jpg"],
    target: "export.image.format",
    userAction: "Select an export image format from the Format dropdown.",
  },
  {
    automated: true,
    automatedTestName: "selects image export resolution multiplier",
    browser: true,
    browserTestName: "browser: user selects export resolution multiplier",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Exported image dimensions scale by chosen multiplier.",
    fixture: "export resolution select",
    id: "control.export-image-resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Select an export image resolution from the Resolution dropdown.",
  },
  {
    actionCoverage: ["exportImage"],
    automated: true,
    automatedTestName: "triggers export image download action",
    browser: true,
    browserTestName: "browser: user clicks Export Image button",
    componentType: "panelActions",
    evidence: "exported-bytes",
    expectedObservable: "High-resolution image file downloads.",
    exportArtifactCoverage: "all-required-image-export-behavior",
    fixture: "export image button",
    id: "control.output-export-image",
    kind: "control",
    target: "output.exportImage",
    userAction: "Click the Export Image action button in the sticky footer.",
  },
];

export const appControlSectionInventory: readonly ToolcraftControlSectionInventoryEntry[] = [
  {
    entity: "Workstation",
    entityId: "workstation",
    groupingReason: "Switch workstation views, browse creative effects, and manage image library.",
    id: "workstation",
    targets: ["panel.activeView", "effect.selected", "source.image"],
    title: "Workstation",
  },
  {
    entity: "Background",
    entityId: "background-section",
    groupingReason: "Configure background color and export background transparency.",
    id: "background-section",
    targets: ["export.includeBackground", "appearance.background"],
    title: "Background",
  },
  {
    entity: "Image Export",
    entityId: "image-export.part-export-image-format-1k2loow",
    groupingReason: "Configure export image format and resolution.",
    id: "image-export.part-export-image-format-1k2loow",
    targets: ["export.image.format", "export.image.resolution"],
    title: "Image Export",
  },
];
